### ISSUE TITLE
Runtime exception thrown: Didn't get expected file information for pub/HomoloGene/current/homologene.data (3 attempts). 

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1016]
[Gemma - pool-158-thread-1 (2024-02-01 16:22:27,059)] ERROR ubic.gemma.core.loader.util.fetcher.FtpFetcher.fetch(177) | Runtime exception thrown: Didn't get expected file information for pub/HomoloGene/current/homologene.data (3 attempts). 
 Stack trace follows:

[Slack Message](https://pavlidis-lab.slack.com/archives/C061Q25PAJH/p1706833347891549)

**Comment by ppavlidis** [comment]
fixed
