### ISSUE TITLE
Boosting performance of queries for Gemma Browser

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#1023]
Performance has continued to improve but we should look for further gains.

The main drag right now is calls like [this](https://gemma.msl.ubc.ca/rest/v2/datasets/annotations?category=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000635&filter=taxon.id%20%3D%201&limit=200&exclude=parentTerms&retainMentionedTerms=true&excludedTerms=H4sIAAAAAAAAE5XTzWrDMBAE4Bcqknb1Y6m3pqQhhzaF%2Bh5s4yahdhQcG7dvX6gp8sXs%2Bv6xjMTMue9vj1Lehq4RsYzNpeyK7kfE7iRjGeXH4aiUUuizh%2FMkT3XbFqK9N2IoK1EVMl57me%2B2r5MEptNMZ5iOlw8Q%2F93Siw%2Bb%2Fd9BhZZLERVF35%2FyKacyfoUNbIsO2DbojGsBMnZe0IF9FxWw8yKkFpBWW82%2Fm9owjqOoy4soKjF8yfozyu3L9FnW0QhM%2Bv1l5IwjkTGpdssoWDqTCRkLaRJZcGQH3p43%2B7z4jtcjKBXIOcw5gFvBQXlywnOu6W3OuUOyPjOOfs1xp8k5J42YebvCz2rKwJ5eX9IOdfgFctbjtCcGAAA%3D).

They take ~5 seconds each.

I'm listing four areas to investigate:

- [ ] One area that might help a little is avoiding tracking free-text categories (which are generally associated with BioMaterial Characteristics imported from GEO) in the EXPRESSION_EXPERIMENT2CHARACTERISTIC table. That will cut the size of that table by a factor of ~2 and the number of categories by a factor of ~500. That may not affect performance as we only query a subset of "proper" categories anyway, but at the very least it will make updating EXPRESSION_EXPERIMENT2CHARACTERISTIC faster.

- [ ] The limit of 200 could also be made less if that affects performance. Bearing in mind the main point of the pre-populated lists of terms is to "show off" what we have in Gemma. We have to balance the desire to show "everything" against the need for the interface to be responsive. If something the user is looking for isn't on the list, they can just search for it. (Either way, we should make it clear in the UI that there is a threshold).

- [x] Another saving is that the table has a lot of redundancy: the same experiment is associated with numerous identical characteristics.  This is because many annotations recur for many samples within an experiment. When we put characteristics in the EXPRESSION_EXPERIMENT2CHARACTERISTIC, they should be unique at the experiment level. That might help speed up the `group by` expression experiment clause that I imagine is required for getting the experiment counts.

For example:

`select * from EXPRESSION_EXPERIMENT2CHARACTERISTIC where EXPRESSION_EXPERIMENT_FK=1 and VALUE="total RNA" ;`

This yields 34 tuples that are identical (other than the primary key) - one per sample. Instead, there should just be one "representative".

- [ ] It's a bit of an aside but I also think 'total RNA' is an example of a term that we can probably exclude from the browser and this table, as it is associated most experiments. There are likely other such terms which are too non-specific/generic to be useful.

**Comment by arteymix** [comment]
I've optimized drastically the retrieval of terms per category. I'm still trying to figure out ways of speeding up the categories query.

I'll explore the possibility of shrinking down the table size. If we manage to drop the ID from the table, or pick an arbitrary one, we'll be able to compress redundant characteristics.

**Comment by arteymix** [comment]
It looks like I can group characteristics by experiment ID, category and value when I populate the table. It results in a considerable reduction in the table size: from 4.7M to 641k rows.

**Comment by arteymix** [comment]
I've brought the time for the category query down to 1.2s uncached by shrinking the EE2C table. I'll see if there are other possible improvements.

**Comment by arteymix** [comment]
The browser also struggles to display so many terms in the dropdown. This can be resolved in the frontend by tuning the number of terms and maybe enable lazy-loading when the dropdown is toggled.

**Comment by arteymix** [comment]
Omitting free-text categories would disrupt features in the browser for little query performance improvement, since those are easily excluded by the table index.

I'll look next into optimizing the browser itself.

**Comment by arteymix** [comment]
I've included a few optimizations for the ontology inference in the 1.31.3 branch.

I think the backend performance is good enough for now. I'll merge the filter caching optimization in the next patch release.
