### ISSUE TITLE
Force DEA heatmaps to be column-sorted by the relevant factor

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#1035]
For example, in https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE124326

Currently the DEA heatmap for biological sex looks like this:

<img width="506" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/4c5a4dcd-c4e2-4d82-8ea8-7e7a20e9db20">

Needless to say, the baseline and contrasting condition should be presented as groups.

We should provide a parameter to the heatmap generation code to force a selected factor (or factors) to be used for sorting first.

(Another wish-list item is to make these interactive so the user could change what is sorted by, but we have no support for interactivity in that part of the interface)

**Comment by arteymix** [comment]
Is there a specific order by which factors should be picked? 

When sorting values, we can try to always have the baseline on the first position.

The heatmap is generated on the fly, so making it to nteractive is not out of reach.

I'm envisioning the following use cases:

-  pick a specific factor value and show the rest of the heatmap
- pick a specific gene or group of genes
- go to the next page of genes sorted by decreasing statistical significance

**Comment by ppavlidis** [comment]
We currently have a heuristic for choosing which factor to sort on first. Typically: the one with the fewest factorvalues, but continuous ones are treated specially and might override the other sorting - I haven't looked to refresh my memory on the specifics. And we try to put the baseline first. 

But it is not (AFAIK) sensitive to which factor might be more interesting to the viewer, which is the point of this issue. So if the user is looking at the heatmap for the "sex" effect, then it should be sorted by sex. If they are looking at the "drug treatment" effect, then it should be sorted by drug treatment (and then by sex within those groups, for example).  The same sorting should be applied when they click on the download link to get the data from the heatmap.

That way, the user will see visually the expression pattern that was associated with a small p-value.

So the "primary factor" needs to be a parameter passed to the server-side data generator.

Interactivity is a "nice to have" and not directly relevant to this, and probably should be made a separate issue.

**Comment by ppavlidis** [comment]
This should be helped somewhat by 26607e2b5e139d8353f3e98ac815fd1b8a27527e, which changes the behaviour when continuous factors are present.

**Comment by ppavlidis** [comment]
The revised implementation takes a factor (or factor ID) to pick as the first one to sort on ("primary"). This could be further improved to allow further ordering to be specified as in the case of interaction effects being displayed, but this is enough for now. The internal cache of layouts is now stratified by which factor was forced to be the primary. (I'm not confident that the cache actually improves performance that much, but for large experiments it may be noticeable)
