### ISSUE TITLE
API uses an inconsistent definition of bioassays and missing relevant information in the datasets endpoint

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#1040]
Bioassays are not equivalent to sample sizes in gemma since sometimes samples are represented by more than one chips. I believe this dataset is such an example

https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=362 (requires admin)

This dataset has 3 samples but 6 bioassays, as can be seen by the datasets endpoint (https://gemma.msl.ubc.ca/rest/v2/datasets/362). Of note, the sample count information is not available within this endpoint which I believe should be available in some form.

However there is also inconsistency in the way the term "bioassay" is used within the FilterArgs. If I use the filter `bioAssayCount < 4`, 362 will be present in the results since in this context it seems to be counting samples (https://gemma.msl.ubc.ca/rest/v2/datasets/?&filter=bioAssayCount%20%3C%204%20and%20id%20%3D%20362 requires admin)

**Comment by ppavlidis** [comment]
Yes, biomaterials can be used in more than one bioassay. 

However, this is always temporary (during curation) and no public data should have this situation. Curation will result in multi-platform datasets (either what we call case 1 or 2) will be resolved into a single expression data matrix on one platform (sometimes a "merged" one). Of course the API should work reasonably for non-public data, just pointing out why this happens.

We also used to allow one bioassay to have more than one biomaterial, but that was for two-color arrays and I don't think we explicitly support that any more as we limit to reference-based designs anyway.

**Comment by oganm** [comment]
I was able to find this inconsistency in some public datasets too. And for the example above it was also after processing so I doubt it is about the curation stage.

For instance asking the datasets endpoint dataset 1506 appears to have 240 bioassays

https://gemma.msl.ubc.ca/rest/v2/datasets/1506

But that actually amounts to 121 samples if we look at the website https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=1506 (not sure why not exactly half in this case)

And using the query `bioAssayCount = 121 and id = 1506` will bring it up (https://gemma.msl.ubc.ca/rest/v2/datasets/?&filter=bioAssayCount%20%3D%20121%20and%20id%20%3D%201506)

**Comment by ppavlidis** [comment]
Ok I suspect some data corruption. File a curation issue with a list of the suspects

**Comment by arteymix** [comment]
This is a bug, the number of samples is denormalized in the `ExpressionExperiment` model. 

https://github.com/PavlidisLab/Gemma/blob/88eb7adc154c19fee3649a1726bf150bba2e5e8d/gemma-core/src/main/java/ubic/gemma/model/expression/experiment/ExpressionExperiment.java#L71-L85

I'll fix it in the database.

We need to change that definition in the future because it will become problematic with single-cell data where we create sub-biomaterials and bioassays to match cell aggregates.

**Comment by ppavlidis** [comment]
We update this field in SplitExperiment and VectorMerge, but not in PlatformSwitch, which may be a culprit.

**Comment by arteymix** [comment]
Ok, I've fixed all the entries in the database. Let's address the code issue in the next patch release.

**Comment by arteymix** [comment]
I couldn't identify other code location where those values can diverge.

**Comment by arteymix** [comment]
I've included another improvement in d4eb69e5235357acc7e71467c98d99a7c9bf90fb to detect cases involving direct calls to setBioAssays().
