### ISSUE TITLE
get_result_sets endpoint lies about isSubset

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#1045]
Dataset [442](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=442) has a differential expression analysis with a subset. Using the getDatasetDifferentialExpressionAnalyses endpoint returns the correct information

https://gemma.msl.ubc.ca/rest/v2/datasets/442/analyses/differential

here the analysis with the ID 290951 has `isSubset` set to `true`

Trying to access the same information using the get_result_sets endpoint however

https://gemma.msl.ubc.ca/rest/v2/resultSets?datasets=442

has it set to `false` and `subsetFactor` is set to null despite managing to populate the `subsetFactorId` and `subsetFactorValue` fields

**Comment by arteymix** [comment]
In that case, it is not being populated properly. I'll investigate this.

**Comment by arteymix** [comment]
I figured it out, the thawing process was not initializing the subset factor value.
