### ISSUE TITLE
typography changes mess up layouts

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#1063]
https://gemma.msl.ubc.ca/arrays/showArrayDesign.html?id=229

<img width="633" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/90e34f32-e501-43dc-8d59-0f2211c2a8f9">

The text in the top section is now too large and you can't see everything. The layout itself needs to be revised, or the text taken down a size or two to bring it back to what it was.

There may be other comparable situations on other pages, I haven't checked.

**Comment by arteymix** [comment]
I've added various classes for sizing fonts consistently: `small`, `smaller`, `normal`, `large`, etc. Those can be used to make local adjustments.

**Comment by arteymix** [comment]
This is also affecting the font size in the heatmap. I'll review the whole website and make adjustments.
