### ISSUE TITLE
Platform annotations endpoint returns a gzip while claiming to return a text file in specification

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#1066]
I believe this issue is identical to what we had before. The specification claims to be returning a raw text file but what we actually get is a gz file. Currently this causes the python wrapped to fail

https://gemma.msl.ubc.ca/rest/v2/platforms/1/annotations

**Comment by arteymix** [comment]
Fixed in 2a4af2662070b19a9c1ae6317d31e2bf9a021002

**Comment by oganm** [comment]
Is it live anywhere?
