### ISSUE TITLE
Documenting enums in api specification

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#1080]
There are fields that appear as text to the end user but actually discrete enums. It would be nice if we could see the possible range of enums just by looking at the specification. It does appear that openapi supports [enums](https://swagger.io/docs/specification/data-models/enums/)

**Comment by arteymix** [comment]
These enums are mapped to string in the VOs. I need to add annotations so that the possible values are populated.

**Comment by arteymix** [comment]
![image](https://github.com/PavlidisLab/Gemma/assets/1318477/5198bf01-dec5-4b9a-85fa-760dcde74ce2)

:)

**Comment by arteymix** [comment]
I'm filling all the enums right now.

**Comment by arteymix** [comment]
Fixed in 69b84c9db687478b6a441a70f4bbacf3f9748914

**Comment by arteymix** [comment]
@oganm  I've also updated https://github.com/PavlidisLab/gemmapy/pull/22 for you to review.
