### ISSUE TITLE
/annotations/search endpoint seemingly providing redundant information

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#1084]
When using an ontology term with search_annotations endpoint, the results include quite a bit of redundancy. For instance, in this search:

https://gemma.msl.ubc.ca/rest/v2/annotations/search?query=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000540

there are 3598 elements but only 12 of them are unique values, rest are just copies of each other.

The same doesn't seem to occur when using plain text to search

https://gemma.msl.ubc.ca/rest/v2/annotations/search?query=neuron

**Comment by arteymix** [comment]
URI search goes straight to the database. This sounds like the query misses a group by and return all the instances of characteristics of matching datasets.
