### ISSUE TITLE
Use of * in queries miss valid results

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#1106]
When * is used to specify a prefix in a query, we seem to be missing some valid results in the output.

For instance the dataset id 6685 which has the ammon's horn annotation is not returned when using *

https://gemma.msl.ubc.ca/rest/v2/datasets/?filter=id%20%3D%206685&query=hippocamp%2A

However using the term hippocampus directly does return it

https://gemma.msl.ubc.ca/rest/v2/datasets/?filter=id%20%3D%206685&query=hippocampus

**Comment by arteymix** [comment]
I'm wondering if the `*` is getting escaped somehow because `hippocamp` is working. I'll investigate this.

**Comment by arteymix** [comment]
@oganm can you test this on the staging server now? The DNF extraction was not including wildcard and prefix terms. Those are now passed to the ontology search index.

**Comment by oganm** [comment]
Seems to be working!
