### ISSUE TITLE
/annotations/children returns 404 for a valid URI

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#1124]
http://purl.obolibrary.org/obo/CLO_0037279 is an up to date ontology term. 

we have datasets annotated with it

https://gemma.msl.ubc.ca/rest/v2/datasets?filter=allCharacteristics.valueUri%20%3D%20http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCLO_0037279

though we don't seem to be propagating to it's child terms. 

but annotations/children endpoint claims it is not a real term

https://dev.gemma.msl.ubc.ca/rest/v2/annotations/children/?uri=http:%2F%2Fpurl.obolibrary.org%2Fobo%2FCLO_0037279&direct=false

**Comment by arteymix** [comment]
I'll look into this since we're going to backport the endpoints in the next patch release.

**Comment by arteymix** [comment]
It's been backported, enjoy!
