### ISSUE TITLE
Args that don't support compression that could use supporting compression

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#1154]
- `/resultSets`, datasets, possibly databaseEntries, I am unsure what this field is.
- `/datasets/{datasets}/expressions/differential`, datasets
- `/datasets/{datasets}/expressions/genes/{genes}`, datasets and genes
- `/datasets/{datasets}/expressions/taxa/{taxa}/genes/{genes}`, datasets and genes
- `/datasets/{datasets}/expressions/pca`, datasets
- `/datasets/{datasets}` datasets
- `/genes/{genes}`, genes
- `/platforms/{platform}/elements/{probes}`, probes

**Comment by arteymix** [comment]
It's completed. I've also added `minItems` and better descriptions.

The only `AbstractArrayArg` subclasses that are not supporting compression are `ExcludedArg` and `TaxonArg` since it makes no sense.
