### ISSUE TITLE
Curation interface request: duplicate factor values

### ISSUE THREAD

**Issue by xnrxng** [PavlidisLab/Gemma#1160]
It would make curation faster if there was a button/option in the interface that would allow you to duplicate/clone factor values.

For example, in [GSE224747.2](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE224747.2), the factor value "embryo stage + has developmental stage" is triplicated, with only a change in the free text value.
<img width="918" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/99299002/a9b18a8f-8513-42e1-a203-c65fd8b04ade">

 Or [GSE149073](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE149073) where the factor value "IACS-10759 + delivered at dose + 135 nM + delivered for duration + 24 h" is found duplicated, with only a change in an appended characteristic.
<img width="917" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/99299002/6068b884-6508-4f0c-b6b4-97f893463fa5">

Could this be added whenever possible? Thank you!

**Comment by arteymix** [comment]
That can be entirely done in the frontend. We'll look into it!

**Comment by ppavlidis** [comment]
has testing been completed for this? Just want confirmation so we can close the issue.

**Comment by xnrxng** [comment]
I have tested this a couple more times and it seems like everything is okay so far, so I'll be closing this issue now.
