### ISSUE TITLE
pagination for getDatasetsDifferentialAnalysisResultsExpressionForGene

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#1161]
an issue with this endpoint (apart from name size inflation) that makes it quite a bit less useful for a proper analysis right now is that it limits the results to 2000. virtually every gene will have more than 2000 resultSets associated with them in gemma so we end up getting an arbitrary cross section of results rather than being able to extract all data available for a gene.

ideally this would be paginated to be able to extract everything

**Comment by arteymix** [comment]
I also noticed that I did not backport the grouping by result set ID. I'll include all results.

**Comment by arteymix** [comment]
I can implement an offset/limit on the datasets being retrieved, but not on the results themselves.

**Comment by oganm** [comment]
That is fine I assume dataset offset will ensure all results can still be returned

**Comment by arteymix** [comment]
Yes.

I might make improvement to this in the future to paginate the actual results, but as it is now it seems impractical to query.
