### ISSUE TITLE
Endpoints returning resultSets failing to return all results

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#1162]
It seems that endpoints with pagination that returns resultSets currently fail to return all results. Two examples I found were the new `/datasets/analyses/differential/results/genes/{gene}` endpoint and the `/resultSets` endpoint, the latter both in production and staging.

Consider an example with 41 resultSet ids, setting filter to `id in (560592, 533761, 541261, 541262, 549019, 549020, 549021, 560596, 560597, 560598, 560599, 514692, 526232, 526233, 526234, 541334, 562675, 562676, 562680, 512773, 558134, 560674, 560675, 560676, 560681, 560682, 560689, 560690, 560719, 560729, 560738, 560739, 560741, 560737, 560736, 560740, 560746, 560747, 560761, 549232, 549233)`, we also set `limit` to a 100 

The [output](https://gemma.msl.ubc.ca/rest/v2/resultSets?filter=id%20in%20%28560592%2C533761%2C541261%2C541262%2C549019%2C549020%2C549021%2C560596%2C560597%2C560598%2C560599%2C514692%2C526232%2C526233%2C526234%2C541334%2C562675%2C562676%2C562680%2C512773%2C558134%2C560674%2C560675%2C560676%2C560681%2C560682%2C560689%2C560690%2C560719%2C560729%2C560738%2C560739%2C560741%2C560737%2C560736%2C560740%2C560746%2C560747%2C560761%2C549232%2C549233%29&offset=0&limit=100&sort=%2Bid) will only have 31 elements returned while claiming to contain 41 elements in it has 41 elements in`totalElements` 

The remaining 10 elements can be accessed by attempting to paginate over the apparent limit, if we set offset to 100 now, we will get the rest: [output](https://gemma.msl.ubc.ca/rest/v2/resultSets?filter=id%20in%20%28560592%2C533761%2C541261%2C541262%2C549019%2C549020%2C549021%2C560596%2C560597%2C560598%2C560599%2C514692%2C526232%2C526233%2C526234%2C541334%2C562675%2C562676%2C562680%2C512773%2C558134%2C560674%2C560675%2C560676%2C560681%2C560682%2C560689%2C560690%2C560719%2C560729%2C560738%2C560739%2C560741%2C560737%2C560736%2C560740%2C560746%2C560747%2C560761%2C549232%2C549233%29&offset=100&limit=100&sort=%2Bid)

So currently it is unclear what we are paginating over and how many pages we should be flipping to get to the end

**Comment by oganm** [comment]
Looks like for larger queries, fixing pagination still results in missing results

**Comment by arteymix** [comment]
I think those might be subset results. The set of IDs I'm getting from filtering datasets should be expanded with subset IDs.

**Comment by arteymix** [comment]
It looks like all the results are present according to @oganm. There are still a few rough corners to address, but the endpoints are working as expected.
