### ISSUE TITLE
/annotations/search endpoint returns incorrect results

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#1195]
It appears that /annotations/search endpoint returns incorrect value-value.URI pairings on occasion. Some examples are

- [http://www.ebi.ac.uk/efo/EFO_0004425](https://gemma.msl.ubc.ca/rest/v2/annotations/search?query=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0004425) 
    - initial time point, returns other specific time points like 6h.
- [http://purl.obolibrary.org/obo/OBI_0000025](https://gemma.msl.ubc.ca/rest/v2/annotations/search?query=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000025)
    - reference subject role, returns  Aspergillus pneumonia and 6d

This may be related to some misannotations within gemma but trying to search for the datasets using the filters failed so far. Another possibility is predicate pairings returning wrong term from the statement as a match

**Comment by ppavlidis** [comment]
Yes, free text annotations of time point won't have a URI but it would be part of a Statement. 

`select * from CHARACTERISTIC WHERE VALUE_URI='http://purl.obolibrary.org/obo/OBI_0000025' and VALUE <> 'reference substance role';` returns three records (one with a NULL class so it is probably not active)  those are some kind of curation or conversion error. Factor values 266568 and 81940. I'll investigate the other term later and take it to the curators.

**Comment by arteymix** [comment]
@oganm is this still affecting you?

**Comment by oganm** [comment]
The examples given seem to be returning the correct results now
