### ISSUE TITLE
Premature termination of addGeoData when "subsidiary" (splitByTaxon) EE contains no Samples

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#120]
Refer this issue: https://github.com/PavlidisLab/GemmaCuration/issues/22

As original identified issue, when a derived EE contains no samples, the output returns a null object. I propose adding a filter such that null EE objects are removed from the Collection before downstream processing takes place. Logging may also be included as necessary.

Line: https://github.com/PavlidisLab/Gemma/blob/25ce88c2b4d27b03c67800c1e928ceca028d6f27/gemma-core/src/main/java/ubic/gemma/core/apps/LoadExpressionDataCli.java#L236

**Comment by ppavlidis** [comment]
Didn't intend to close it, do so after it's rolled out and confirmed to fix the original report issue.
