### ISSUE TITLE
Postprocess attempted when loading RNA-seq (minor)

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#121]
See end of https://github.com/PavlidisLab/GemmaCuration/issues/4 and log attached there.

If this happens repeatedly we'll hopefully be able to track it down.

This doesn't have any effects on proper loading of data, so this is largely an aesthetic issue AFAIK.

**Comment by arteymix** [comment]
Postprocessing is working reliably now.
