### ISSUE TITLE
500 error produced by a search query

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1225]
[Gemma - http-nio-8181-exec-118 (2024-09-15 12:49:00,681)] ERROR ubic.gemma.rest.providers.AbstractExceptionMapper.toResponse(65) | Unhandled exception was raised for GET <http://localhost:8181/rest/v2/datasets/annotations?category=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0005135&amp;filter=&amp;limit=200&amp;exclude=parentTerms&amp;retainMentionedTerms=true&amp;query=Space%20Flight%20%22&amp;excludedTerms=H4sIAAAAAAAAE5XSzQrCMBAE4BeSJLv5aeNNQcWDKOhdmlLbYmukthTfXjBITyXr%2FWOYXabq%2B%2BeS8%2BfQNcw739Suy7o3813JvfP8fLwKIQSmyaIKsizaNmPtq2GDy1mecf%2Fo%2BWW3OQQJRCeJThEdrR8g%2Ftzcxcf1%2FhsoUFMpoojR0%2BoSegqV%2FmEt2aIBsrUyoVqAhNwXpCXnogByX4RpBVErtaTnTmsYx5EVrmZZzoY7L26eb7bhWdrEEajp%2B%2FPIKBNFSk2zm0dWxzspm5CQjCINJv0ARgdHsycEAAA%3D&amp;excludeFreeTextTerms=true&amp;gid=turecki>

[Slack Message](https://pavlidis-lab.slack.com/archives/C02LZHP6RB3/p1726429741233149)

**Comment by arteymix** [comment]
Hmm, can't reproduce this right now. I'm not sure what exactly triggered that.

**Comment by oganm** [comment]
Still looking into this but it is possible that there is an issue on your end as well. 

This query for `\?` as far as I can see is correctly encoded, yet fails with a 500

```
https://gemma.msl.ubc.ca/rest/v2/datasets/?query=%5C%3F
```

**Comment by arteymix** [comment]
Interesting, let me test that!

**Comment by arteymix** [comment]
Seems to be fixed.
