### ISSUE TITLE
Add HANCESTRO and AFPO to the basic set of ontologies

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1286]
EFO only partly imports from HANCESTRO and does not have any term from AFPO.

Now that we have those terms in the replacements, we should have the ontologies as well.

It might be enough to just include HANCESTRO.

**Comment by ppavlidis** [comment]
I doubt this is worth the bother.

**Comment by arteymix** [comment]
Ok, let's close this then
