### ISSUE TITLE
Rework experiment search (for "GSE..." cases) so that both pre-split and post-split datasets are also displayed

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#140]
Currently, the search function will stop further searches if it finds an experiment that has the exact match to the query - particularly for queries using a "GSE..." pattern. Due to more active use of manual splitting, and the retention of the pre-split datasets, all post-split datasets (i.e. .1, .2, .n) are not displayed.

Until all pre-split datasets are safely removed, there is some merit to being able to search for both the pre- and post-split dataset concurrently, so that curators and administrators are aware of both types of datasets when performing searches (otherwise only the pre-split datasets are retrieved during a search).

Reference Issue: https://github.com/PavlidisLab/GemmaCuration/issues/54

**Comment by ppavlidis** [comment]
This is an easy fix, but just realize it may slow down searches for everybody since we would require another search step to be executed even when the GSENNNNN gets a hit. Hopefully it isn't noticeably slower.

**Comment by ppavlidis** [comment]
My fix (en route) just does extra searching if the user is an admin, to avoid this slowing down other users

**Comment by ppavlidis** [comment]
Confirmed to work https://gemma.msl.ubc.ca/searcher.html?query=GSE151460
