### ISSUE TITLE
How to find Significant SNPs from the results of GEMMA

### ISSUE THREAD

**Issue by sekhwal** [PavlidisLab/Gemma#158]
Hi,
I have got the results of BSLMM at GEMMA. I have files such as prefix (bv.txt, gamma.txt, hyp.txt, log.txt, param.txt). However, I am not very familiar with these results. Please let me know how to find significant SNPs from these results. I am looking to calculate multiple correction using bonferroni at p-value but I can not see the p-values in the GEMMA results files.

Thank you,

**Comment by ppavlidis** [comment]
Hi, Gemma does not contain data on genetics nor ways to analyze the files you mention and you may be confusing it with some other tool. Please refer to https://pubmed.ncbi.nlm.nih.gov/33599246/ for more information about Gemma.

**Comment by sekhwal** [comment]
Can you take a look here https://www.xzlab.org/software/GEMMAmanual.pdf. I am surprised to get your answer.

**Comment by ppavlidis** [comment]
Wrong lab, wrong Gemma, there is no relationship.
