### ISSUE TITLE
Experimental Tags containing "[" or "]" fail on click for search

### ISSUE THREAD

**Issue by Tu1026** [PavlidisLab/Gemma#166]
Right not the default behaviour when clicking on an experimental tag, Gemma will successfully query other experiments with similar tags in the database as shown here
![image](https://user-images.githubusercontent.com/64434778/125831674-bf21ceb8-25f3-4899-84fc-816a2d285b86.png)

However, it seems to break whenever I click on the term [Cell Line Sample Study] and I would get this error
![image](https://user-images.githubusercontent.com/64434778/125831875-4eebac20-cf22-43de-82ce-e0270c2befd8.png)
<br>
Even simply typing in [Cell Line Sample Study] search, the same error message would show up as well
![image](https://user-images.githubusercontent.com/64434778/125831835-b0d6dc4e-3278-442e-b7f1-b3f0559616ec.png)

*Note: Indeed other terms with the "[" and "]" also broke as well. I tested "[Sample Study]" and "[Benchmark study] and they broke as well.

**Comment by ppavlidis** [comment]
I still don't know how to get to the result you are showing, please provide a link. And are those "[" in the actual TGEMO ontology? That's kind of weird.

**Comment by Tu1026** [comment]
Using [GSE13421](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=1845) as an example. I can replicate the error by clicking on the experimental tag directly like this.
![image](https://user-images.githubusercontent.com/64434778/125836608-26bae2b8-8e94-48de-8802-cb50f60a9a3e.png)

I believe they are actual TGEMO terms as there are URLs attached to them and they can be found in the documentation [here](https://wiki.pavlab.msl.ubc.ca/display/gemma/Curate+the+Experimental+Tags)

**Comment by ppavlidis** [comment]
confirmed fix works on dev.gemma
