### ISSUE TITLE
Replace geoscrape

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#169]
We've gone through two iterations of ways to bulk-identify datasets for inclusion in Gemma.

It started with using Gemma tools in conjunction with some bash scripts to process and filter the results.

The next stage was [searchGEO](https://github.com/PavlidisLab/searchGEO) aka geoscrape. But we have run into limitations and since it's written in matlab, it's annoying to maintain.

There is a very simple CLI GeoGrabberCli that already handles retrieving summary records from GEO using eutils, and returns them as GeoRecords. This uses a GeoBrowserService which also underlies the [browser interface in Gemma](https://gemma.msl.ubc.ca/admin/geoRecordBrowser.html). 

This corresponds to XML files like the attached [esummary.xml.zip](https://github.com/PavlidisLab/Gemma/files/6871358/esummary.xml.zip)
, using Eutil queries (in this case with a search term and a range of records to retrieve):

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=gds&term=gse[ETYP]+AND+Homo+sapiens[orgn]&retstart=10&retmax=10&usehistory=y

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=gds&&mode=mode.text&query_key=1&retstart=10&retmax=10&WebEnv=MCID_60fb38acd45ef85fce15c04b

In this use case, we wouldn't use a search term but would apply search terms after the fact, since we can have a long list of them.

Any information in that file can be used for additional processing, but it is fairly minimal - it doesn't include super/subseries details. Maybe they offer richer xml formats, something to investigate.

So I propose that we expand the service and/or CLI front end for this to suit our scraping needs, and any functionality that isn't best supported there can be done with additional external scripts in Python. 

Features we need:

- [x] Check if platform is already in the system and provide indication (already supported by the browser)
- [x] Check for blacklist status of experiment and platform (need to add this)
- [x] Avoid checking the same experiments over and over
- [x] Output as a table that is convenient for review.
- [x] It needs to search the same fields that the searchGEO does - have to check what they are.

**Comment by Tu1026** [comment]
Would it be possible to not retrieve single-cell/nano string/Chip-seq and other not supported datasets? (Or at least as few of those experiments as possible).

**Comment by AlexAdrian-Hamazaki** [comment]
![GEOscrape workflow](https://user-images.githubusercontent.com/77304943/127038351-cbd11bd8-983d-47da-93cd-c9f96c331749.jpg)

I've made up this flowchart that closely represents our current workflow. Many of these scripts are already functional and tested, and those that arn't can be easily made from by modifying others. I don't propose that we add this functionality into the scrape. I'm simply wanting to make clear our process of external filtering. 

My major goal right now is to clean up these scripts and push them to the Gemma Curation github in a nicely packed folder that future curators can easily understand and use.

**Comment by AlexAdrian-Hamazaki** [comment]
Right, as mentioned by wilson, nanostring, iontorrent etc platforms can be annoying to deal with. A Filtering step for these platforms could be added to this flowchart as well if we don't want to add it to the actual scraping conditions

I think it best to scrape not limit the scrape based on single-cell, platform type etc, and to instead just get all of the GSEs that contain the relevant search terms. From there we can easily filter based on our specific limiting factors. I think this is important because the platforms and experiment types that we support might change in the future.

**Comment by ppavlidis** [comment]
I'd prefer not to have hard-coding of any "avoid" terms, but the option to have that as an input is fine. Remember this program is hopefully going to be used for a long time so it should be generic and future-proof without having to change the code (ideally). 

Avoiding platforms we don't want is difficult to make foolproof if the platform isn't already blacklisted. One way to do that would be for curators to proactively search GEO for such platforms and blacklist them. For example, there are 277 hits for platforms in GEO for "nanostring". The hits can be downloaded as text (not in a very nice format, but can be munged easily enough).

**Comment by AlexAdrian-Hamazaki** [comment]
> One way to do that would be for curators to proactively search GEO for such platforms and blacklist them.

That would also work for affymetrix, ion torrent; but correct me if I'm wrong, we wouldn't be able to do this for scRNA, lnc, miRNA.

**Comment by ppavlidis** [comment]
> That would also work for affymetrix, ion torrent; but correct me if I'm wrong, we wouldn't be able to do this for scRNA, lnc, miRNA.

Yep. For platforms it is reasonably straightforward to make a list and blacklist them, but for experiment types that would basically be doing the curation job in reverse. Best to do that after the fact. There's no getting around that some manual screening would be necessary at some point.

**Comment by ppavlidis** [comment]
I've enhanced the existing `listGEOData` CLI. We get these columns at the moment:

- Accession
- ReleaseDate
- Taxa
- Platforms
- AllPlatformsInGemma (boolean)
- NumSamples
- Type (of experiment e.g. Sequencing)
- SuperSeries (boolean)
- SubSeriesOf (a GSE accession or blank)
- PubMed (if present)
- Title
- Summary (the paragraph)

It's a little slow, partly because to determine whether a dataset is a subseries, we have to do a second query, and I don't see a way to batch that - it has to be done one experiment at a time. 

The output is filtered to skip data sets:
- That already exist in the system
- That don't use at least one supported taxon
- That don't include at least some "expression profiling" type
- That are blacklisted
- That only use blacklisted platforms

You can enter either a date at which the search should stop (e.g., the date of the previous scrape), or a GSE (since the way these queries work is it goes in reverse order). The latter probably isn't as foolproof as maintaining a list of experiments we have already checked, but it is simple.

There is no screening for specific terms (e.g. 'brain'). My idea is that the output of this would then be used to search for experiments. The nice thing about that is we can just run it once (periodically) and use the same output repeatedly. 

One thing that my program doesn't do is output information on all the samples. I believe Aman's program does look at that but I'm not too sure how. I'm not too sure of the value added, it would make the output very verbose to dump everything, but I also only seem to get the sample names, not any details. But probably there are other queries we can do to fetch more info and add it to the output.

**Comment by AlexAdrian-Hamazaki** [comment]
> * Summary (the paragraph)

I would suggest also including the "Overall Design". In my experience it would be worth scraping just knowing the types of things that are commonly included there. 


> You can enter either a date at which the search should stop (e.g., the date of the previous scrape), or a GSE (since the way these queries work is it goes in reverse order). The latter probably isn't as foolproof as maintaining a list of experiments we have already checked, but it is simple.

I'm a bit confused here because I thought that the point of maintaining a list of experiments we already scraped is that we could just refer to the list to see if we've parsed, so we don't have to parse them again. As we discussed maybe last month, if we search a range of GSEs and then move onto another range, then we will miss GSEs that have gone public in our previous ranges. I guess we search up to a previous date, like 5 years ago. However, I'd be concerned about what we would do in the next years, would we keep the date the same? or would we move the date window down? Perhaps I'm not understanding something about the new workflow that you're envisioning here as your initial screen wouldn't be using search terms?



> There is no screening for specific terms (e.g. 'brain'). My idea is that the output of this would then be used to search for experiments. The nice thing about that is we can just run it once (periodically) and use the same output repeatedly.

Should Wilson and I take a look at Aman's code and see what his search terms are? We could then just use regex to filter out the experiments that are hits. This is the simplest way I can think of,  and as we discussed, I don't think those "scores" are pertinent.

**Comment by ppavlidis** [comment]
The "overall design" field isn't in the XML I'm getting, unfortunately.

AFAIK the "release date" refers to when it was made public so we should have less need to maintain a list of what has been scraped before (see below). My method works as follows (ignoring the filtering steps):

1. Use Eutils to query the most recently released GSEs - currently doing 100 at a time.
2. Retrieve the esummary.xml using eutils for the batch, extract everything useful
3. Retrieve a MINiML file for each experiment where I can find if a GSE is a subseries (and what is the superseries)
4. Retrieve pubmed xml for any associated publication for each experiment, extract mesh headings (rarely will be present unless paper is at least several months old)
5. Retrieve the associated sample MINiML file so I can get the Characteristic and Treatments for each sample.
6. Return to step 1 to retrieve the next batch of experiments going backwards in time.
7. Keep going until we reach the start of GEO or hit a limit set by the user (date or specific GSE).

Note that I am never querying for a specific GSE - I get the list of them from GEO and then fetch the details. The reason that you had to maintain a list of already-screened experiments is because of how Aman's script works. I believe Aman does something like query GSE1, GSE2 ... GSEn, which I agree is likely to miss newly released GSEs that are out-of-order-numerically. He also has to deal with what happens when data isn't public, since he is still getting (partial) responses for those.

My method shouldn't have those problem, it's based on dates. As long as we trust their eutil to give us things in reverse time order correctly (always has...), it should be okay.

The difficulty with a list is how to maintain that file, because each time it also has to be updated and different curators need to know where to find it (like, I don't know where it is). So a simple solution seems to me that you just enter the date of the last time a scrape was done, which still requires bookkeeping but we should be keeping track of that anyway. Certainly I can add the option to add a "skip" file as well if that's better but I don't see that.

As for how to screen afterwards: the file I provide includes all experiments that pass the filters mentioned above, so it can be re-filtered any way we want. But I suggest that someone write a script (python would be good) to do that. Let's discuss separately.
