### ISSUE TITLE
Taxa endpoint not accepting string input

### ISSUE THREAD

**Issue by yavyx** [PavlidisLab/Gemma#175]
This endpoint should accept string input (e.g. 'human', 'mouse', etc.) but is returning a 400 error at the moment.

Example:
https://gemma.msl.ubc.ca/rest/v2/taxa/human

Numerical inputs (https://gemma.msl.ubc.ca/rest/v2/taxa/1) work as expected. 

This test used to pass in the R wrapper, so it should be a recent change.

**Comment by arteymix** [comment]
Fixed in 96349ca0d82873b874d32cb399eda414a2cddf76
