### ISSUE TITLE
Add rate limiting to API endpoints

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#177]
- from Apache, there are various modules available
 - using a Servlet filter (like https://reddog.mx/rate-limit.html)
 - within the REST API code with RateLimiter from Guava and Semaphore

**Comment by ppavlidis** [comment]
This is now done. @dima-v-v when you get a chance can you add a note here briefly explaining the solution and close the issue.

**Comment by dima-v-v** [comment]
The rate limitation has been implemented at Apache which serves as the app proxy. It is base on mod_qos Apache module (http://mod-qos.sourceforge.net/) which is capable limiting access based on configurable rules. In this case we limit:
1. the total number of concurrent connection to  /rest/v2/datasets/\*/data url to **two** as this type of  request (\*/data) takes a specially long time to process.
2. the rate to all REST API requests (/rest/v2 url) to **10 req/sec**:
