### ISSUE TITLE
filter in Dataset endpoint doesn't accept database name

### ISSUE THREAD

**Issue by Billy-Zhoup** [PavlidisLab/Gemma#181]
Hi, I have a question about Gemma

Could you give me an example about how to use the filter in Dataset endpoints?

Like I want to filter the datasets which are not from GEO?

**Comment by arteymix** [comment]
Hello there!

To make this work, you can filter the `externalDatabase` attribute from the accession of the `ExpressionExperiment` as follow:

```python
requests.get('https://gemma.msl.ubc.ca/rest/v2/datasets', 
    params={'filter': 'accession.externalDatabase.id != 3}))
```

Let me know if you use another programming language than Python. You must URL-encode the "=" character for it to work.

https://gemma.msl.ubc.ca/rest/v2/datasets?filter=accession.externalDatabase.id%20!%3D%203

It should normally work by name (i.e. `accession.externalDatabase.name != GEO`), but I think there's an issue with that, so you can use the numerical id instead.

**Comment by arteymix** [comment]
This is related to #175 It appears that I broke string comparison. I'll add a test for filtering by string and debug the issue.
