### ISSUE TITLE
Incorrect string values when using newer MySQL connector

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#186]
This issue is due to the fact we are using a latin1 database, and we're inserting characters that don't have a proper representation from external sources (i.e. GEO).

 - [x] remove explicit character set and collate in model definitions a9113c5be0366cef4bd0c741848753851ed25405
 - [x] use utf8mb4 by default for tests c24dcde9e2bbe487d491646432dfda9a1f32093b
 - [x] use utf8mb4 in the production database (will require some work that must be performed before the release)
 - [ ] adjust migrations scripts? I'm not exactly sure about this part and how migration works, so some input from @ppavlidis would be helpful here

The purpose of removing explicit character sets and collates in our Hibernate configuration is that these are inherited from the table and the database. To address this systematically, we need to alter the database CS and collate, not every single text column. This is done for tests, but it will require some work for the production database.

I don't expect any loss of data since UTF-8 is a superset of latin1, and that our external sources are supplying data in UTF-8. For all it's worth, we've already lost data when converting text with the older database driver.

We can also change the character set and collate without downtime, since the model definitions are only used for creating the tables, not querying them.

The contingency is to revert the connector and the commits above.

**Comment by arteymix** [comment]
Good. The build is passing for the dev, and it's running fine right now. There might be errors related to invalid characters, but that will require a change of character set in the database.

**Comment by ppavlidis** [comment]
About the migration scripts: we keep track of schema changes but the reality is that none of that is really relevant after the fact. We have the only live instance of the database AFAIK. I'm referring to the ones in gemma-core/src/main/resources/sql/migrations. If you mean something else let me know.

**Comment by arteymix** [comment]
The migration has been performed successfully. The next release will take advantage of this with a newer MySQL driver.
