### ISSUE TITLE
Experiment External GEO Association Not Working 

### ISSUE THREAD

**Issue by Tu1026** [PavlidisLab/Gemma#207]
![image](https://user-images.githubusercontent.com/64434778/137200462-92beecee-9e03-4e85-ad82-1cb6bf9fe704.png)
Following up on our conversation before, some experiments have this "Direct Upload" status instead of the GEO link that they should have. This would go away wait on the page for a minute or two and refresh the page. The next image shows the result of me refreshing the page after a little bit.

![image](https://user-images.githubusercontent.com/64434778/137200712-9ac2d417-20b1-45b2-82f2-9ccfdc27c7e2.png)

**Comment by ppavlidis** [comment]
I mentioned I suspect this might be some caching issue, but not sure; it's a new problem since the last code updates.

**Comment by arteymix** [comment]
Is this problem still happening? I had to disable VO caching for EEs and ADs because it resulted in missing accession/geeq scores.
