### ISSUE TITLE
Unresponsive Web application and 100% CPU usage

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#234]
Last time it occurred was on November 3rd and started around 8AM until the service was restarted. You can see below the last load peak.

![image](https://user-images.githubusercontent.com/1318477/140178607-7efe9272-8680-4621-9bbf-9f427879c5ba.png)

For some reason, I was unable to attach a debugger to the process and investigate the root cause. I checked, and the debugger setup appears to work just fine.

**Comment by arteymix** [comment]
I managed to grab a stack trace: [gemma-chalmers-stack.txt](https://github.com/PavlidisLab/Gemma/files/8157646/gemma-chalmers-stack.txt) using jstack.

Notable facts:

 - the Compass reindexer is running
 - ubic.gemma.core.job.executor.webapp.SubmittedTaskLocal.addEmailAlert() is opening some kind of ZIP file
 - there are dozen of ubic.gemma.persistence.service.association.coexpression.CoexpressionQueryQueueImpl$1.run()

Also, I don't think the Slack appender is working correctly because I can see a number of threads attempting to report something.

**Comment by ppavlidis** [comment]
OK interesting. The CoexpressionQuery stuff is what catches my eye. This is part of a system to pre-fetch coexpression data. I don't know why run would be called repeatedly, that sounds like a bug.

As noted elsewhere, coexpression is a likely target of deprecation in Gemma. Not going to to that now but we can just disable this cache, it or at least greatly reduce how much prefetching it does.

**Comment by arteymix** [comment]
I noticed that this often happens when ontology are being loaded or updated.

**Comment by arteymix** [comment]
We caught another instance of Gemma going haywire and becoming unresponsive. I manage to get a stacktrace with `jstack -F`:

[Gemma stacktrace on August 23rd 2022.log](https://github.com/PavlidisLab/Gemma/files/9410423/stacktrace.log)

**Comment by arteymix** [comment]
This is resolved. The culprit were ontology services using an insane amount of memory when initialized.

I have another fix in upcoming baseCode 1.1.15 that removes term caching altogether, limiting te memory usage over time to what Jena needs. If caching is necessary, it should be performed in Gemma with EhCache.
