### ISSUE TITLE
Revise quantitationType tab in EE page

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#24]
* Make it possible to download the data for any quantitation type
* Clean up some of the confusing columns we have there like "normalized" and "background subtracted". Will discuss.

**Comment by tesar-stepan** [comment]
Paul via Slack:
The main new feature is to make is possible to download the DataVectors (as a text matrix file) for any quantitation type. The download link on the main tab for each experiment is basically doing that for the ProcessedData (though in that case the files are generated offline - but the method is the same, using ExpressionDataFileServiceImpl.writeOrLocateDataFile might work). So it would be another column to the quantitation type table, the QT is probably the only parameter needed.

**Comment by tesar-stepan** [comment]
It has been decided to completely hide the QT tab for non-administrators at the moment.
