### ISSUE TITLE
Failure when trying to view heatmap of DE genes

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#255]
e.g. https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=609
click on the orange "histogram" sorta icon, yields a "data could not be displayed" error.

This has not worked any time I have tried it in the last few days, for any experiment, so I am starting to doubt it is a problem with specific data sets.

**Comment by arteymix** [comment]
Ok, I'll look into it.

**Comment by arteymix** [comment]
It's a missing @Transactional annotation on getDiffExVectors. Hibernate does not like load + thaw in separate transactions. I think that closing the session in-between breaks the proxy objects.

**Comment by arteymix** [comment]
I think we used to reload models from scratch when thawing instead of reusing the passed entity, so it would bypass the need for a session throughout the operation.
