### ISSUE TITLE
AssertionError in AllenBrainAtlasServiceTest.testGetGene

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#286]
There's a warning, which might be related:

```
[gemma-core 2021-12-16 09:35:56,415] WARN [main] ubic.gemma.core.image.aba.AllenBrainAtlasServiceImpl.getGene(84) | ABA XML file did not contain gene ID or symbol.
```

**Comment by ppavlidis** [comment]
This is a feature we will be removing

**Comment by arteymix** [comment]
Ok. It's only affecting the development branch so far. I haven't had the chance to rerun the CI for the stable release, but I suspect this error will arise.

I can schedule the removal for the next minor release of Gemma. This test never passed on my dev setup.
