### ISSUE TITLE
Display version tag in production when current user is an administrator

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#289]
I understand that we don't want to display meaningless numbers to our users, but it would be really handy for administrators to see the version tag to ensure that deployments were successfully performed.

**Comment by ppavlidis** [comment]
That should already be the case, at the bottom of pages, it is part of the template?

**Comment by arteymix** [comment]
It's the case only in development, but I think it's somewhat hidden in production.

**Comment by arteymix** [comment]
It seems that the `gemme.version` is missing from the looked-up properties. This is a build issue related to #199.

**Comment by arteymix** [comment]
For some obscure reason, it works on the dev instance...

**Comment by arteymix** [comment]
I'm starting to suspect that a dependency is shadowing `version.properties`. in the classpath resolution. I'll review all our dependencies to see if that is the case.

**Comment by arteymix** [comment]
It could also be tested indirectly by renaming the file with a proper namespace.

**Comment by arteymix** [comment]
That was exactly the problem! I'll still review the deps to find out the culprit.
