### ISSUE TITLE
NullPointerException when accessing experimental design for GSE3895

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#361]
See https://github.com/PavlidisLab/GemmaCuration/issues/236

**Comment by arteymix** [comment]
Logs not super helpful:

```
[Gemma - http-nio-8181-exec-497 (2022-05-11 13:22:29,742)] WARN org.directwebremoting.util.CommonsLoggingOutput.warn(67) | Method execution failed: 
java.lang.NullPointerException: null
[Gemma - http-nio-8181-exec-497 (2022-05-11 13:22:29,743)] WARN org.directwebremoting.util.CommonsLoggingOutput.warn(67) | --Erroring: batchId[0] message[java.lang.NullPointerException]
java.lang.NullPointerException: null
```

**Comment by arteymix** [comment]
This is caused by an `ExperimentalFactor` with a NULL category. This is allowed by the database model unfortunately. I can change this if it is a bug.

 @ppavlidis

**Comment by ppavlidis** [comment]
We might need to allow this if curators are saving data before finishing filling it in, or we could add a check that requires it be populated. But I'm not sure how this crept in.

**Comment by arteymix** [comment]
There are 3 such cases in the database:

![image](https://user-images.githubusercontent.com/1318477/181834416-14e083ea-ab18-4532-b38c-cc41b2155f1d.png)

With such low IDs, they were probably introduced early in the software. I will change the data model to non-null.

**Comment by arteymix** [comment]
I fixed the database column type in the data model. I will add a migration.

**Comment by arteymix** [comment]
As for the curator part, they must choose one of the existing available option which already has a corresponding characteristic entry.

**Comment by arteymix** [comment]
I had to revert the non-null change and instead handle all potential null-cases. The switch to non-null will be considered another time in #397 .
