### ISSUE TITLE
Mulformatted table with Rest API /resultSets/{resultSet} endpoint

### ISSUE THREAD

**Issue by dima-v-v** [PavlidisLab/Gemma#365]
The file requested in the following way:
_curl 'https://gemma.msl.ubc.ca/rest/v2/resultSets/444829?&offset=0&limit=20&sort=%2Bid' --compressed -H 'Accept:text/tab-separated-values' > table.txt_
has one line, #11529, with 10 tabs vs 13 tabs (all other lines). A bug is suspected.

**Comment by arteymix** [comment]
That's annoying because it means not all results have the same contrast. This is most likely a bug.

I think we use the first one for reanalysis and it's probably the best thing to rely upon for consistency sake. 

I would also include a log.error() for the problematic results.

**Comment by arteymix** [comment]
It appeared that a single result had this issue:

> [Gemma 2022-08-03 12:20:52,328] WARN [http-nio-8080-exec-2] ubic.gemma.core.analysis.service.ExpressionAnalysisResultSetFileServiceImpl.writeTsvToAppendable(91) | DiffExRes[761009488]: CompositeSequence Id=1009317 Name=1389637_at p=null ressetId=444829 is missing contrast result for [FactorValue 17488: Treatment:vehicle | 0.9% NaCl | reference substance role | , null]. The corresponding column in the TSV will be treated as NaN.

Maybe @tkim98 could look into this?

**Comment by arteymix** [comment]
I can't find the source experiment for the analysis... maybe the result set is detached?
