### ISSUE TITLE
Disappearance of 'Organism Part' Category on Gemma

### ISSUE THREAD

**Issue by tkim98** [PavlidisLab/Gemma#410]
Alice has noticed that the 'Organism Part' EFC is no longer listed as a category on Gemma. Looks like it is only showing up as its EFO ontology (EFO_0000635).

<img width="602" alt="Screen Shot 2022-08-25 at 11 51 12 AM" src="https://user-images.githubusercontent.com/89932772/186745246-3e6a2e44-6037-4faf-a611-5c23c34fbc29.png">

**Comment by arteymix** [comment]
It sounds like the representative record for the term is missing a name in the database. Maybe it wasn't saved with one? I'll investigate.

**Comment by ppavlidis** [comment]
Categories are at least partly connected to the EFO.factor.categories.txt config file
EFO is read into memory on app startup
It should not be relying on a record in the DB but I'm not sure why this would happen so I could be wrong

**Comment by arteymix** [comment]
Yeah, I deleted this because it is wrong. The terms are resolved in the database. This suggests instead that there's something missing in the in-memory ontology.

**Comment by ppavlidis** [comment]
Since we fetch EFO from an external site, perhaps there is an issue with that file, which would be unusual but possible and hopefully temporary. In other words, this might be resolved next time we restart the app.

**Comment by arteymix** [comment]
It seems to have resolve itself.

![image](https://user-images.githubusercontent.com/1318477/198080469-e6d2d702-d46e-4916-9f06-19fad8c074fd.png)

**Comment by tkim98** [comment]
It still seems to show up as its EFO ontology for me
<img width="223" alt="Screen Shot 2022-10-26 at 9 21 53 AM" src="https://user-images.githubusercontent.com/89932772/198080928-17760bf4-f853-4b9a-a1dc-9e94f9f19657.png">

**Comment by arteymix** [comment]
I'll try to restart Gemma, it's only fixed on the development server.

**Comment by tkim98** [comment]
I see, thank you!

**Comment by arteymix** [comment]
It was just a matter of restarting Gemma.
