### ISSUE TITLE
Dev branch: search result details aren't shown

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#411]
e.g. 

https://dev.gemma.msl.ubc.ca/searcher.html?query=grin1

I first spotted this with a local build.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/206415/187294470-ba29e5af-7028-4780-b116-26454b9f54fe.png">

**Comment by arteymix** [comment]
It broke because we're not using ValueObject classes anymore for typing search results. The type is actually immutable now, only the result can be substituted for a VO. I'm fixing this by replacing some text in the frontend code.
