### ISSUE TITLE
Result objects are null for this search query

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#417]
Full URL from Ogan: https://dev.gemma.msl.ubc.ca/rest/v2/search?query=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFCL_0002368&limit=20

**Comment by arteymix** [comment]
@oganm do you have another example that produce a null result object?

**Comment by oganm** [comment]
all expressionexperiments in this one turns up null

https://dev.gemma.msl.ubc.ca/rest/v2/search?query=bipolar&limit=1000

**Comment by arteymix** [comment]
The stored object in the index is `null`.

**Comment by arteymix** [comment]
Hmm, turns out Compass is not at fault here, the object becomes `null` after being converted to a VO. I'll investigate a bit more...

**Comment by arteymix** [comment]
Filtering for non-null result objects has no effect. This must then be the JSON serialization that renders the object null.

Sounds like a very nasty bug to me. I'll see if I can enable Jackson debug logging...

**Comment by arteymix** [comment]
Awesome, all the EEs that are null result from `CharacteristicService.findExperimentsByUris`! I was suspecting an issue with compass, but that sounds more like some kind of Hibernate proxy interfering with Jackson.

![image](https://user-images.githubusercontent.com/1318477/194624178-b6ec39e3-f62f-43a1-9f3e-78fb1588180b.png)

**Comment by arteymix** [comment]
Ok, I fixed the by characteristic null EEs. The one remaining originate from Compass:

![image](https://user-images.githubusercontent.com/1318477/194634394-56d1035f-b74b-4f6b-bfd5-17cdae128691.png)

Making progress!

**Comment by arteymix** [comment]
There are a few cases still originating from `findExperimentsByUris` that are nullified due to ACL filtering later on. I'm adding an ACL clause to the query.

**Comment by arteymix** [comment]
Completely fixed by 24813d65f858094afc07e6bae19b853f10de474c
