### ISSUE TITLE
Cannot read properties of null (reading 'addClass')

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#421]
This seems to be related to some commented-out code in the frontend.

Uncaught TypeError: Cannot read properties of null (reading 'addClass')
    at sb.render (ext-all-debug.js?d=1722200951:11419:32)
    at HomePageAnalysisSearch.js?d=1720571756:38:18
    at ext-all-debug.js?d=1722200951:209:15
    at call (ext-all-debug.js?d=1722200951:1566:13)

**Comment by ppavlidis** [comment]
I believe the offending line is `searchForm.render( "analysis-results-search-form" );`

That can be commented out, the target div is indeed commented out. But I will let you do that so you can test it more quickly.

**Comment by arteymix** [comment]
Perfect!
