### ISSUE TITLE
ArrayDesign VO statistics are not filled for the Gemma Web

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#424]
![image](https://user-images.githubusercontent.com/1318477/190514948-ec853a14-e1cc-480e-9603-0f312d31cdce.png)

v.s. dev:
![image](https://user-images.githubusercontent.com/1318477/190515043-c057c383-c663-47b8-97a9-e84aa268d6c9.png)

**Comment by ppavlidis** [comment]
The little files used to populate that box are separate for production and dev. 

To create them, you can log in as an administrator (on dev) and click the "refresh" button in the box. I don't know why the unique genes would be filled in though, so maybe there is something else going on.

**Comment by arteymix** [comment]
I was wondering why it was empty on my development setup but then realized this gets filled in the controller layer.

We will not be exposing those fields in the REST API for now.
