### ISSUE TITLE
qvalue is never filled in DiffExResultSetSummaryValueObject

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#431]
Via code inspection, there is no writing of this field. I'm also wondering where this value could be retrieved from.

Maybe @ppavlidis can weigh on this.

I'm setting this for a later release since we cannot address this in the present release cycle.

Related to #422, where it turned out it was the only field worth hiding in the VO.

**Comment by ppavlidis** [comment]
I believe this field is used in javascript. I think it's meant to be the threshold used to determine DE genes for the summary.

See DifferentialExpressionAnalysesSummaryTree.js.

**Comment by arteymix** [comment]
Ok, I'll keep it then. I just switched its annotation to `@GemmaWebOnly`.
