### ISSUE TITLE
Review which fields from AnnotationValueObject should be visible

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#436]
![image](https://user-images.githubusercontent.com/1318477/192881667-30507420-2652-41fe-b0a1-7ce5099fd60a.png)

**Comment by ppavlidis** [comment]
This class is used for GO terms as well as our own annotations of things like biomaterials.

I don't think the parent* fields are going to be relevant for API methods (some are probably not used anywhere)

It will help me answer if you indicate which fields are even populated. 

For "typical" uses of Annotations, you'd want the class and term information and possibly the evidenceCode (I think description is only used for GO terms?). 

The objectclass is used to indicate the class of object that is annotated which can be useful in the UI, but not sure for the web api.
