### ISSUE TITLE
Review which fields from CoexpressionValueObjectExt should be exposed

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#440]
![image](https://user-images.githubusercontent.com/1318477/192886537-7083ed56-a101-4301-8d68-9b8688400b1b.png)

We can also hide the gene coexpression endpoint if necessary.

**Comment by ppavlidis** [comment]
These are all used by the web interface. containsMyData is an indicator that should probably be deprecated since we're not allowing data uploads by outside users any more. sortKey is something to aid sorting in tables in the UI.

**Comment by arteymix** [comment]
The model will not be exposed it we mark the endpoint as hidden. We can decide later if and how to expose gene coexpression.
