### ISSUE TITLE
Platform name incorrectly parsed from CLI when creating merges

### ISSUE THREAD

**Issue by tkim98** [PavlidisLab/Gemma#453]
Theres seems to be a bug in the CLI for merging platforms that parses the merged platform name such that only the first word is captured. For the example below, only "Agilent" is recorded for the name:

`gemma-cli mergePlatforms --array GPL10787 --other GPL21163 --name "Agilent Sureprint G3 Mouse GE 8x60K Microarray" --shortname "Agilent_8x60K_Merged"`

This error occurred previously and was suspected to be a shell quoting error however I did retype the quotes this time around only to encounter the same issue. I have already updated the name in the database now.

**Comment by arteymix** [comment]
I suspect this could be due to a misnamed CLI option. @tkim98 I'm preparing you a patch build for you to test.

**Comment by arteymix** [comment]
There likely won't be a 1.27.19 release.

@tkim98 It's ready now, can you try `/space/grp/gemma-cli-1.27.19/bin/gemma-cli`?

**Comment by arteymix** [comment]
The code change is cosmetic and likely won't be enough, I'll have to debug the command...

**Comment by arteymix** [comment]
I think I figured it out, I use the following line in the wrapper script:

```
exec /space/grp/gemma-cli/bin/gemma-cli $@
```

The spaces within the name is treated as different arguments...

**Comment by arteymix** [comment]
Fixed!

The solution is simple:

```
exec /space/grp/gemma-cli/bin/gemma-cli "$@"
```
