### ISSUE TITLE
QC Notification for experiments with poor sample correlation

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#47]
Case-In-Point: https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=9000

For an Illumina BeadChip platform, this experiment has very poor sample-sample correlation. Implementation of an automated check to flag such occurences to the curator for further investigation.

Related Slack thread continues from this point: https://pavlidis-lab.slack.com/archives/C41KJ0THV/p1516818864000656?thread_ts=1516756950.000009&cid=C41KJ0THV

**Comment by tesar-stepan** [comment]
Sample-sample correlation will be part of GEEQ. I am currently calculating lowest mean, median and variance. Median is used for quality score calculation, the other two properties are currently stored but not used for anything. I do plan on introducing 'hints' in the admin section on how to improve score (e.g. remove outliers, run batch correction etc.), so this would be the place I would also notify curators if one of the properties is under certain threshold.

**Comment by ppavlidis** [comment]
Considering this closed as GEEQ is implemented and user-visible.
