### ISSUE TITLE
Disappearance of DEA Results 

### ISSUE THREAD

**Issue by tkim98** [PavlidisLab/Gemma#475]
Alice and I have noticed several experiments that had DEA previsouly run successfully but the results have now disappeared from the experiment's home page on Gemma:

<img width="555" alt="Screen Shot 2022-10-17 at 10 40 50 AM" src="https://user-images.githubusercontent.com/89932772/196248358-c773a51e-f253-497f-86b2-59299e36c960.png">

There have been a few instances where the results have returned the next day but for others, like [GSE2127](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE2127) above, even re-running DEA fails to recreate the graphs.

**Comment by arteymix** [comment]
This sounds like a caching issue.

The web frontend and the CLI can sometimes diverge because they do not share the same cache.

**Comment by ppavlidis** [comment]
[GSE2127](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE2127) works for me.

**Comment by arteymix** [comment]
It's probably been fixed with the work on making preprocessing service more robust.
