### ISSUE TITLE
AuditEventService.getLastEvent() method and related methods return the oldest AuditEvent

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#48]
As title, instead of returning the latest AuditEvent, the method returns the oldest AuditEvent. I suspect this might be a side-effect of the History-sorting functionality?

(Other affected methods include ExpressionExperimentService.getLastProcessedDataUpdate() )

**Comment by tesar-stepan** [comment]
Thank you for spotting this. Yes that is most likely the result of me messing with the audit trail - I recently inverted the order of events by date. I will have a look at it promptly.

**Comment by tesar-stepan** [comment]
This should now be fixed, please reopen if the problem still appears somewhere
