### ISSUE TITLE
Search yields error when term has quotes

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#480]
searching for `collection of material` works but doesn't give useful results. Trying `"collection of material"` gives an error.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/206415/197048943-4f7d3de7-f8fe-490e-b6cd-d8190133b81d.png">

https://gemma.msl.ubc.ca/searcher.html?query=collection%20of%20material&scope=P,G,E,A,M,H,N,B

**Comment by arteymix** [comment]
That's because "" are escaped with back quotes by Lucene's query escaper. The resulting string is sent to both the database and compass sources. It makes no sense to escape at this moment. Each source should handle its source-specific escaping.

**Comment by arteymix** [comment]
That's one, I fixed the escaping of characters in query by making it source-specific.

Another related issue I found was in `PhenotypeAssociationManagerServiceImpl`, where a whildcard would be appended right after a quote, resulting in an invalid query such as: `"collection of materials"*`. I'll only add a wildcard now if the last character is not a `"`.

**Comment by arteymix** [comment]
I'm adding unit tests for these various behaviours...
