### ISSUE TITLE
[MINOR] GemmaWeb generated Differential Expression Analysis Files are missing Probe-Gene Annotation

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#49]
Case-In-Point:
https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=522

Problem:
When invoking the "Download Differential Expression Analysis Files" from GemmaWeb, the individual analysis files in the zip files are missing the probe:gene mapping annotation. Example:
`Element_Name	Gene_Symbol	Gene_Name	NCBI_ID	FoldChange_3.hours	Tstat_3.hours	PValue_3.hours	FoldChange_24.hours	Tstat_24.hours	PValue_24.hours	FoldChange_72.hours	Tstat_72.hours	PValue_72.hours
1370651_a_at			0.1310	0.3014	0.7659	0.03988	0.09173	0.9277	-0.1496	-0.3441	0.7340`

List of what are not the problems:
1. Are the probes in the array mapped to genes? Yes. (https://gemma.msl.ubc.ca/arrays/showArrayDesign.html?id=2)
2. Is the information shown in "Visualize Experiment" Tab? Yes. [Example uses the same probe in the case shown above] (https://gemma.msl.ubc.ca/dedv/downloadDEDV.html?ee=522&g=961033)

**Comment by tesar-stepan** [comment]
This seems to be a problem only with EEs on platforms that do not have annotation files generated. For the analysis file generation, the microannot. files are used to get the probe-gene mapping. Unfortunately, once the analysis zip file is generated, it is never checked for changes and gemma always returns the old file.

**Comment by tesar-stepan** [comment]
I have generated the annotations file for the platform id 2 and regenerated the analysis file for the experiment id 522.
