### ISSUE TITLE
Increase maximum and default results limit for search endpoints

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#504]
There might also be a case for no maximum limit at all, or some large internal cap to prevent accidental retrieval of absurd amout of records.

**Comment by ppavlidis** [comment]
I recommend a cap of 2000 and a default of 100.

**Comment by arteymix** [comment]
It turns out the endpoint Marine was using all had an `offset` option for navigating by pages. I'll nonetheless increase the maximum default we have to something more useful.

**Comment by arteymix** [comment]
Fixed in 2f09e086eb2 (capped at 1000) and subsequently to 2000 in a3836499cb411c3c664b123bd5f55007a96cea99. There's already an internal cap of 300 for Compass and in 3bd708cb85b40712581dd2020bab6b7864b5277a in made the maximum number of results more consistently applied.
