### ISSUE TITLE
web search yields "characteristic value objects" with no actual usable results

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#511]
I believe this category shouldn't be there at all.

https://gemma.msl.ubc.ca/searcher.html?query=vasopressin&scope=P,G,E,A,M,H,N,B

<img width="572" alt="image" src="https://user-images.githubusercontent.com/206415/206050197-bcbe1056-32cc-43c5-864d-bb3480721958.png">

**Comment by arteymix** [comment]
This is caused by an incorrect result type for phenotype associations.
