### ISSUE TITLE
batch correction badge should only be shown if done after last data replacement

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#57]
It is possible for a data set to be batch corrected, and then the data replaced via (e.g.) raw data analysis. It is no longer batch corrected. 

In general the badges should reflect the last valid event, which can depend on what later events have happened.

**Comment by tesar-stepan** [comment]
The batchEffect property is updated automatically each midnight for all experiments that have been updated during the previous day. I'll check if this works properly.

**Comment by tesar-stepan** [comment]
The automated batch info script was broken. Fixed and updated to be more robust in 8cc6ab1ad1c665a8c49a82a454277a0e68a5baf7
The same commit also forces recalculation after experiment processing.
