### ISSUE TITLE
Certain EVs from public experiments are inaccessible for the /rest/v2/data/processed endpoint

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#574]
The ACLs need to be reviewed.

@oganm

**Comment by arteymix** [comment]
I fixed a lot of ACLs in 1.30 with the gsec cleanup. @oganm can you verify this issue still occurs on the dev instance?

**Comment by oganm** [comment]
quantitationTypes endpoint still denies access to unauthenticated users:
- https://dev.gemma.msl.ubc.ca/rest/v2/datasets/1/quantitationTypes

and processed data endpoint seem to return an error regardless of authentication status
- https://dev.gemma.msl.ubc.ca/rest/v2/datasets/1/data/processed

**Comment by arteymix** [comment]
Fixed in a00d8582ae9a20f72240b3762cc40d5c282f66f4 and 86a02a824507c0669eeccb776af1888f1367b17e.

I'll backport this in the next patch release if needs be.
