### ISSUE TITLE
Consistency when referring to genes throughout the API

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#575]
The way one can refer to genes appears to be rather inconsistent between endpoint to endpoint without an intuitive reason. I'd want to know if these differences were intended and/or inevitable

- getDatasetExpressionForGenes endpoint seems to explicitly be using NCBI ids. not symbols or the internal gene ID.
    - https://gemma.msl.ubc.ca/rest/v2/datasets/1,4/expressions/genes/55885?keepNonSpecific=false works while https://gemma.msl.ubc.ca/rest/v2/datasets/1,4/expressions/genes/LMO3?keepNonSpecific=false doesn't
- this doesn't appear to be a hard rule
    - https://gemma.msl.ubc.ca/rest/v2/datasets/3/expressions/genes/Copg1?keepNonSpecific=false works
- when getting GO terms for genes, using a symbol seems to return the results for zebrafish genes.
    - Symbol: https://gemma.msl.ubc.ca/rest/v2/genes/LMO3/goTerms
    - Zebrafish id: https://gemma.msl.ubc.ca/rest/v2/genes/553774/goTerms
    - Mouse id: https://gemma.msl.ubc.ca/rest/v2/genes/109593/goTerms
    - Human id: https://gemma.msl.ubc.ca/rest/v2/genes/55885/goTerms
    - Rat id: https://gemma.msl.ubc.ca/rest/v2/genes/497798/goTerms
    
While zebrafish likely isn't the best default choice, this could be made more clearer if we added the information about which gene we resolved to when returning the go terms.

To my understanding, best supported and preferred way to refer to genes are NCBI ids. symbols appear untrustworthy and inconsistent, and internal IDs are never used. Would it make sense to not support symbols at all to promote consistent outcomes?

**Comment by arteymix** [comment]
For the endpoints that retrieve gene directly, we should expect unambiguous IDs. This applies to `/genes/{geneIds}` endpoints.

To add the taxon context and making IDs unambiguous, we can add the aforementioned endpoints under `/taxa/{taxonId}/genes/{geneIds}`.

When a dataset is referred (i.e. `/datasets/{id}/expressions/genes/{geneIds}`, we should use the taxon of the dataset as a constraint for matching by symbols. If more than one gene is matched by symbol within a taxon, we can return all the relevant rows.

**Comment by arteymix** [comment]
This is a significant amount of work and I want to get the 1.30 out soonish, so I'll schedule this for the 1.31.

**Comment by arteymix** [comment]
Looks like this can make it into the 1.31.6 ;)
