### ISSUE TITLE
Differential Expression Analysis Fails for certain RNA-Sequencing Experiments (No Data Error)

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#58]
Cases-In-Point:
https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=8912
https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=9578
https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=9593

They share a common error, sample stacktrace included below:

`Note: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.commons.math3.exception.NoDataException: no data at ubic.gemma.core.analysis.expression.diff.LinearModelAnalyzer.runAnalysis(LinearModelAnalyzer.java:1382) at ubic.gemma.core.analysis.expression.diff.LinearModelAnalyzer.doAnalysis(LinearModelAnalyzer.java:682) at ubic.gemma.core.analysis.expression.diff.LinearModelAnalyzer.run(LinearModelAnalyzer.java:506) at ubic.gemma.core.analysis.expression.diff.LinearModelAnalyzer.run(LinearModelAnalyzer.java:380) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) at com.sun.proxy.$Proxy210.run(Unknown Source) at ubic.gemma.core.analysis.expression.diff.AnalysisSelectionAndExecutionServiceImpl.analyze(AnalysisSelectionAndExecutionServiceImpl.java:63) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) at com.sun.proxy.$Proxy160.analyze(Unknown Source) at ubic.gemma.core.analysis.expression.diff.DifferentialExpressionAnalyzerServiceImpl.runDifferentialExpressionAnalyses(DifferentialExpressionAnalyzerServiceImpl.java:177) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) at com.sun.proxy.$Proxy163.runDifferentialExpressionAnalyses(Unknown Source) at ubic.gemma.core.apps.DifferentialExpressionAnalysisCli.processExperiment(DifferentialExpressionAnalysisCli.java:386) at ubic.gemma.core.apps.DifferentialExpressionAnalysisCli.doWork(DifferentialExpressionAnalysisCli.java:119) at ubic.gemma.core.util.AbstractCLIContextCLI.tryDoWorkNoExit(AbstractCLIContextCLI.java:58) at ubic.gemma.core.apps.DifferentialExpressionAnalysisCli.main(DifferentialExpressionAnalysisCli.java:82) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at ubic.gemma.core.apps.GemmaCLI.main(GemmaCLI.java:114) Caused by: java.util.concurrent.ExecutionException: org.apache.commons.math3.exception.NoDataException: no data at java.util.concurrent.FutureTask.report(FutureTask.java:122) at java.util.concurrent.FutureTask.get(FutureTask.java:192) at ubic.gemma.core.analysis.expression.diff.LinearModelAnalyzer.runAnalysis(LinearModelAnalyzer.java:1377) ... 50 more Caused by: org.apache.commons.math3.exception.NoDataException: no data at org.apache.commons.math3.analysis.interpolation.LoessInterpolator.smooth(LoessInterpolator.java:228) at org.apache.commons.math3.analysis.interpolation.LoessInterpolator.smooth(LoessInterpolator.java:395) at ubic.basecode.math.linearmodels.MeanVarianceEstimator.loessFit(MeanVarianceEstimator.java:260) at ubic.basecode.math.linearmodels.MeanVarianceEstimator.voom(MeanVarianceEstimator.java:369) at ubic.basecode.math.linearmodels.MeanVarianceEstimator.(MeanVarianceEstimator.java:161) at ubic.gemma.core.analysis.expression.diff.LinearModelAnalyzer$2.run(LinearModelAnalyzer.java:1405) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) `

**Comment by tesar-stepan** [comment]
Currently traced the problem to basecode:

`Caused by: org.apache.commons.math3.exception.NoDataException: no data
	at org.apache.commons.math3.analysis.interpolation.LoessInterpolator.smooth(LoessInterpolator.java:228)
	at org.apache.commons.math3.analysis.interpolation.LoessInterpolator.smooth(LoessInterpolator.java:395)
	at ubic.basecode.math.linearmodels.MeanVarianceEstimator.loessFit(MeanVarianceEstimator.java:260)
	at ubic.basecode.math.linearmodels.MeanVarianceEstimator.voom(MeanVarianceEstimator.java:369)
	at ubic.basecode.math.linearmodels.MeanVarianceEstimator.<init>(MeanVarianceEstimator.java:161)
	at ubic.gemma.core.analysis.expression.diff.LinearModelAnalyzer$2.run(LinearModelAnalyzer.java:1407)`

**Comment by ppavlidis** [comment]
This was actually a fairly serious bug in how library sizes were computed. All RNA-seq data sets should probably be re-run for differential expression to be safe.
