### ISSUE TITLE
Choosing genes for the Visualize Expression Tab

### ISSUE THREAD

**Issue by sanjarogic** [PavlidisLab/Gemma#593]
We talked about this briefly at one of the dev meetings. It seems that the genes to be displayed in the heatmap are chosen randomly and often those genes show a weird and non-representative expression pattern. 

For example here where a bunch of miRNA genes is chosen for display:
 
<img width="691" alt="Screenshot 2023-03-06 at 1 49 35 PM" src="https://user-images.githubusercontent.com/32522256/223244180-2945c307-48dd-4f5b-8c3d-dbcee0a47066.png">

Clicking on the "Visualize" button will often generate a better, more informative map, but it's annoying that this needs to be done.

Another issue that sometimes occurs is that there is no heatmap shown, like here:

<img width="683" alt="Screenshot 2023-03-06 at 1 49 06 PM" src="https://user-images.githubusercontent.com/32522256/223244611-c7b124dc-9352-4813-a335-c401e2cd783a.png">

No idea what's happening here, but again, clicking on the "Visualize" button resolves the issue.

**Comment by ppavlidis** [comment]
This is partly a duplicate of #90

Why nothing would be displayed in some cases is a new issue AFAIK

**Comment by sanjarogic** [comment]
I don't think this is only an issue with unmapped probes, it might be that in some cases genes are not expressed. Based on the way I use this tab to see if the data is there and how it looks in terms of quality (e.g. is there a problem with alignment), I would first display genes that are known to be expressed.

**Comment by ppavlidis** [comment]
I'd rather discuss this in #90 to keep things tidy.

**Comment by arteymix** [comment]
This is about picking representative probes which are surely not a random sequential slice of the EVs. By resolving #90, we will have to sample more intelligently.
