### ISSUE TITLE
Enhance detection of scale type from data

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#600]
Follow up of https://github.com/PavlidisLab/GemmaCuration/issues/296 with implementation requirements.

 - [x] consider datasets that have been Z-transformed, detected via mean zero SD 1 to be log-base unknown
 - [x] rule out datasets with zero median too
 - [x] rule out data within zero and one or 0 and 100 which should be treated as percent
 - [x] rule out data with discrete values which are most certainly raw counts
 - [x] create a range over the maximum signal for log2, log10 and linear scales, anything falling outside should be considered log base unknown (basically between the log10 and linear range)
 - [x] consider applying detection sample-wise and gene-wise (data could be Z-transformed either way and possibly both way too)
 - [ ] consider using theoretical distribution (log-normal, normal) test to separate linear and log-transformed cases
 - [x] dump a few samples into tabular format to be used for unit tests
 - [ ] add an audit event when scale type has been guessed and data had to be transformed
 - [x] add a warning intended for the curator when a scale type is guessed
 - [x] apply the above detection even if the scale type is known beforehand, and warn that the data might be incorrectly labelled
 - [ ] run the scale type detection on all existing data as to identify issues
 - [ ] consider the technology type (i.e. detecting counts on a microarray is suspicious)
 - [ ] detect log2 or log10 of ratios such as https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM16534

The best metric to set log-base apart appears to be the maximum for a probe.

It appears to be impossible to distinguish log2 from natural logarithm.

Graph used for determining thresholds:

![image](https://user-images.githubusercontent.com/1318477/224786608-69277438-af1c-45e6-b995-535a0ca8cb38.png)

**Comment by arteymix** [comment]
I will also check if data reported as linear has been log-normalized. Something like:

```R
data <- exp(zscore(log(data)))
```

In which case the log of the data will have zero mean/median.

**Comment by arteymix** [comment]
I ruled out all the datasets that have percent, counts, Z-transformed data, etc. to produce this final plot:

![image](https://user-images.githubusercontent.com/1318477/224850751-4a8d01c9-d3e6-46d0-b65d-bd37edd79ecc.png)

**Comment by arteymix** [comment]
For the [0, 30] region:

![image](https://user-images.githubusercontent.com/1318477/224851051-e48f9c16-d8c7-450f-ad70-b1e165006c05.png)

**Comment by arteymix** [comment]
I analyzed all we have in Gemma:

![image](https://user-images.githubusercontent.com/1318477/224884350-a345a523-a524-42d1-bc51-ac9b929b39ed.png)

![image](https://user-images.githubusercontent.com/1318477/224884408-3b8ffd9b-b472-45b8-9429-6a97a762276d.png)

I think we can use 20 as a cutoff for detecting log10-transformed datasets and $10^{3.2}$ for linear.

**Comment by arteymix** [comment]
It's pretty easy to detect log2 and log2 ratiometric. However, the latter are overlapping log10 which might pose a problem. The peak around zero is the Z-transformed data which we will be detecting separately as Z-scores.

![image](https://user-images.githubusercontent.com/1318477/225165922-d9b0a835-5670-4cce-b1af-0250f0dc1b57.png)

**Comment by arteymix** [comment]
Comparing log10 and log2 ratiometric

![image](https://user-images.githubusercontent.com/1318477/225166326-11ba35f3-be95-4132-866d-8e24f25ea649.png)

I will use the actual `IS_RATIO` labels we have in the database to see if it still holds up.

**Comment by arteymix** [comment]
I fixed the bug with duplicated GEEQ entities when generating processed EVs.

I'm just waiting on gathering more microarray datasets from the database, since it appears to take a very long while (~25 minutes for ~400 datasets). There's 10558 such datasets which would take a combined 10 hours.

**Comment by arteymix** [comment]
Ok, I has something messed up in the query: the BIO_ASSAY jointure created a lot of duplicated rows. I simplified to this:

```sql
select ev.EXPRESSION_EXPERIMENT_FK   as DATASET_ID,
       RAW_QT.ID                     as RAW_QT_ID,
       RAW_QT.SCALE                  as RAW_QT_SCALE,
       RAW_QT.IS_RATIO               as RAW_QT_IS_RATIO,
       ev.ID                         as RAW_VECTOR_ID,
       hex(substring(ev.DATA, 1, 8)) as FIRST_SAMPLE_DATA
from RAW_EXPRESSION_DATA_VECTOR ev
         join QUANTITATION_TYPE RAW_QT on ev.QUANTITATION_TYPE_FK = RAW_QT.ID
         join INVESTIGATION I on ev.EXPRESSION_EXPERIMENT_FK = I.ID
where RAW_QT.IS_PREFERRED
  and I.ID not in
      (select distinct I.ID
       from QUANTITATION_TYPE QT
                join INVESTIGATION I on QT.EXPRESSION_EXPERIMENT_FK = I.ID
       where QT.NAME = 'rma value%')
  and I.ID in (select distinct I.ID
               from INVESTIGATION I
                        join BIO_ASSAY B on I.ID = B.EXPRESSION_EXPERIMENT_FK
                        join ARRAY_DESIGN A on B.ARRAY_DESIGN_USED_FK = A.ID
               where A.TECHNOLOGY_TYPE not in ('SEQUENCING', 'GENELIST'))
```

We'll also be excluding datasets that have been imported from CEL files using Affy tools and focus on data imported from user-submitted data. There's 4,879 such datasets.

**Comment by arteymix** [comment]
We can detect data in the [0, 100] range by adding an extra check on the maximum to set them apart from log-transformed datasets. This successfully detects GSE2.

**Comment by arteymix** [comment]
Ratiometric vs regular log2 

![image](https://user-images.githubusercontent.com/1318477/226057522-e5f197da-6854-4eca-94df-0bbcd80bf76c.png)
![image](https://user-images.githubusercontent.com/1318477/226057469-efec2db5-1842-44f1-a103-6acadc9c32a8.png)

We can delineate log2 ratiometric from log10 by looking at the max most of the time.

**Comment by arteymix** [comment]
We apparently also have a few log2 datasets mislabelled as ratiometric:

![image](https://user-images.githubusercontent.com/1318477/226058888-d5c9be04-3fb4-4249-8ccb-6f299c817198.png)

**Comment by ppavlidis** [comment]
More discussion in #617
