### ISSUE TITLE
CEL file processing doesn't 'unprefer' the existing QT

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#609]
`affyFromCel` , when run successfully, fails to flip the state of 'preferred' for the old (typically GEO SOFT-derived) data to 'FALSE'.

**Comment by arteymix** [comment]
I don't think we anticipated the case of running this command on already imported datasets.

Separately, I also want to review datasets with multiple preferred QTs. I think those get flagged in the UI with multi QT label.

**Comment by ppavlidis** [comment]
Actually, this seems to be a relatively recently introduced problem because it has long been SOP to run the command on already imported data sets , there has never been an option to do anything else.

A bit of history: Originally, Gemma only took data from GEO SOFT files. It was not standard practice for GEO to even require submission of CEL files (or other raw data for other types of platforms). They started asking for this later. 

Eventually we decided it was worth the trouble to reanalyze Affymetrix data from CEL files to help enforce consistency, so this was implemented and was at least attempted on all the Affy data sets we had. At that point, there was no issue with multiple 'preferred' QTs cropping up.

To this day, when we import Affymetrix data sets, we always import the data from the SOFT file, because that was how we did it before, and CEL files are still not always available (it's also common for data sets that have the raw data in GEO to be missing some CEL files or to have a corrupted file; we fall back on retaining the SOFT-derived data in those cases).

So I believe something must have changed relatively recently to expose or create this bug.

The only data type where we _don't_ get the data on first import of the CEL files is RNA-seq, because that is not provided in the SOFT files (if there exceptions to this I don't know).

BTW Yesterday I fixed the multiQT issue for ~40 datasets.

**Comment by arteymix** [comment]
I think the `quantitationTypes` collection were missing `delete-orphan`, which would be fixed by 3ca542062f4a455f62732d776a4906deaab81b51. I removed a lot of unnecessary logic for removing EEs by using appropriate cascading behaviour in Hibernate.

 I'll see if I can add a few assertions in the test case for replacing raw vectors.

**Comment by arteymix** [comment]
Fixed in https://github.com/PavlidisLab/Gemma/pull/610/commits/1c9214d2ba7ac810cdda1f67db85f8baa01f2387
