### ISSUE TITLE
makeProcessedData should redo diff.ex. if it exists

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#616]
I thought this would happen but apparently not.

It's not a big deal to do `diffExAnalyze ... -redo` but it would be a convenience to complete all the post-processing just like we do for `affyFromCel`

**Comment by ppavlidis** [comment]
I also don't think diagnostics are recomputed by default, this should be the case. Again, behaviour should be like `affyFromCel` unless I'm missing something

**Comment by arteymix** [comment]
I guess this is resolved now since we call process and it updates DEA if needed.
