### ISSUE TITLE
Gemma CLI should report the version

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#619]
I thought this used to happen but it's gone.

**Comment by arteymix** [comment]
I introduced a `--version` flag for that purpose in the last release cycle.  think what I'll include the version in the message that displays active profiles.

> Loading Gemma %s (active profiles: %s), hold on!

On the CLI you would get something like:

> Loading Gemma 1.30.0-SNAPSHOT (active profiles: cli, dev), hold on!

**Comment by arteymix** [comment]
This can be ported to the 1.29 series, I just need to strip the profile part as it does not have it yet.
