### ISSUE TITLE
"Expression Images" tab for individual genes shows no images

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#62]
As title, the tab is supposed to show ISH images from the Allen Brain Institute, if I remember correctly, but no longer does so. Communication with Paul suggest that this feature be deprecated.

**Comment by tesar-stepan** [comment]
Fixed in 604b0a08ef2867b1972bb4e04ada36bc083e9312

**Comment by tesar-stepan** [comment]
Improved in 7af3f55746a9082f184b16ac7a0001b21c2ed2c1 and 9ad72d1f2613a7738c267e32f7562d95f2e92281
