### ISSUE TITLE
"No batch effect" badge can be shown incorrectly

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#623]
Example: https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE26740

This dataset has no batch information, and the audit trail does not have any indication of batch information being examined.

This isn't dataset specific, so I'm assuming there is a logic error somewhere. Hopefully a quick fix.

**Comment by ppavlidis** [comment]
Another example https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE153199

**Comment by arteymix** [comment]
For some reason, these datasets have `batchEffect` set:

![image](https://user-images.githubusercontent.com/1318477/229637887-a14cf09c-e617-450f-a3ca-bf7c265ccc04.png)

This is not an UI error, but rather a problem in the logic that infers the batch effect.

**Comment by arteymix** [comment]
OK, I figured it out, the logic is wrong. getBatchStatusDescription() never checks for `hasNoBatchInfo`, but instead rely on the BatchEffectDetails to be null which it never is.

**Comment by arteymix** [comment]
We'll have to run the update batch confound in the GUI to fix those two.

**Comment by ppavlidis** [comment]
Thanks. There's more that just those two, so we might need to do some bulk updating. This should only impact (some) datasets where we are using 'external' data i.e. some microarrays.
