### ISSUE TITLE
Diagnostics M-V plot might be log-transforming data twice sometimes

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#626]
Example: https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE178653

The raw QT is log2, the maximum and I confirm the maximum for the first sample is 878 in **both** the raw data and the processed data. So we are not log-transforming it when we convert it to "processed" - this is correct.

But in the Gemma diagnostics tab the maximum is about 10. Since it’s already log2, we shouldn’t have log-transformed it again but log2(878) is very close to 10 and obviously we don’t show the value of 878 (to be careful: the value plotted there is the average across samples, but as it turns out all the samples have similar values)

I suspect there might be some second check for range in the Mean-Variance thing that shouldn't be there and we are log-transforming again?

**Comment by arteymix** [comment]
THe MeanVariance service uses `filterAndEnsureLog2` on the processed vectors, so unless those are linear, they shouldn't be log-transformed twice before plotting. 

The processed vectors haven't been regenerated for this dataset, so if the raw QT scale went from LINEAR -> LOG2, we would also need to run `makeProcessedData` to have it reflected in the plot.

**Comment by arteymix** [comment]
From the spreadsheet, I saw that the scale was indeed originally LOG2, I don't understand why the data was log-transformed when producing processed EVs.

**Comment by ppavlidis** [comment]
It isn't log transformed again when making processed data. The processed data is fine as noted in the issue.

The only issue is what is going on with the diagnostic plot. I tried to regenerate the diagnostics but it at least partly failed. But the MV part seems to work (?) and be skipping the log transform as intended. Plot looks the same.

```
Computing sample coexpression matrix for ee 19250, regressing: false
Thaw phase 4 62976 vector-associated probes thawed in 337ms
Retaining 50849/62976 rows that have associated BioSequences
Filter summary:
Filter summary for ExpressionExperiment Id=19250 Name=Microarray analysis of mouse retinal organoids (GSE178653):
Started with	62976 (9 columns) 
After Seq	50849
After ZeroVar	42868
After LowExpr	34294
After LowVar	32579
================================================================

Computing sample coexpression matrix for ee 19250, regressing: true
Thaw phase 4 62976 vector-associated probes thawed in 57ms
Filter summary:
Filter summary for ExpressionExperiment Id=19250 Name=Microarray analysis of mouse retinal organoids (GSE178653):
Started with	62976 (9 columns) 
After ZeroVar	51610
After LowExpr	41287
After LowVar	39222
================================================================

ExperimentalFactor Id=37059 Name=timepoint not retained at p=0.027 for PC0
ExperimentalFactor Id=37055 Name=genotype not retained at p=0.73 for PC0
ExperimentalFactor Id=37059 Name=timepoint not retained at p=0.061 for PC1
ExperimentalFactor Id=37055 Name=genotype not retained at p=0.73 for PC1
ExperimentalFactor Id=37059 Name=timepoint not retained at p=0.73 for PC2
ExperimentalFactor Id=37055 Name=genotype not retained at p=0.061 for PC2
ExperimentalFactor Id=37059 Name=timepoint not retained at p=0.96 for PC3
ExperimentalFactor Id=37055 Name=genotype not retained at p=0.027 for PC3
ExperimentalFactor Id=37059 Name=timepoint not retained at p=0.88 for PC4
ExperimentalFactor Id=37055 Name=genotype not retained at p=0.96 for PC4
 | SAMPLE CORR ANALYSIS | Just computed	 | full matrix : Available	 | regressed matrix: Available
Thaw phase 4 62976 vector-associated probes thawed in 58ms
Failed to determine if the data matrix contains microarray platforms: failed to lazily initialize a collection of role: ubic.gemma.model.expression.experiment.ExpressionExperiment.bioAssays, could not initialize proxy - no Session.
The scale of QuantitationType(super=QuantitationTypeImpl Id=550911 Name=VALUE - Processed version, isBackground=false, isBackgroundSubtracted=false, isBatchCorrected=false, isMaskedPreferred=true, isNormalized=true, isPreferred=false, isRecomputedFromRawData=false, isRatio=false, generalType=QUANTITATIVE, representation=DOUBLE, scale=LOG2, type=AMOUNT) differs from the one inferred from data: OTHER.
Data is already on a log2-scale, will not transform it.
11366 rows removed due to low variance
7658 rows removed due to too many identical values
Computing mean-variance relationship
```

**Comment by ppavlidis** [comment]
Another possible case? 

https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE78825

Your reported maximum (for one sample) was 5, but max in diagnostic is barely 2. Both raw and processed are log2.

(That's a crummy dataset so maybe there's some other problem)

**Comment by ppavlidis** [comment]
It's possible that this is because the processed data is out of sync with the raw data, or something. Let's look at these after we do the data processing.

**Comment by ppavlidis** [comment]
> It's possible that this is because the processed data is out of sync with the raw data, or something. Let's look at these after we do the data processing.

I believe this is the issue, so I'm closing this. However, we will need to ensure we  experiments that had their data updated but diagnostics didn't get computed for some reason

https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=23740 was like this but running the diagnostics cleared it up.
