### ISSUE TITLE
NPE on viewing experiment

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#630]
https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=26767

<img width="839" alt="image" src="https://user-images.githubusercontent.com/206415/230489900-36712aee-d635-44ca-b014-da6012c5dd98.png">

**Comment by ppavlidis** [comment]
This happens with every experiment I've checked.

**Comment by arteymix** [comment]
Sorry about that, I did not expect that some of our category terms would be missing from EFO.
