### ISSUE TITLE
Addition of PATO ontology

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#643]
Pato includes some qualifiers (left/right, mature/young) that are no longer imported in any of the ontologies we are using.

Below are the  terms from PATO that are already used in Gemma but no longer supported by our current ontologies, some with plausible replacements offered

https://docs.google.com/spreadsheets/d/1nlFuln9EYDIdo_B3A2XYeJ_RtC3T3cB9H8ANU6iYGYk/edit#gid=1870538327

**Comment by oganm** [comment]
Based on what we have, it looks like importing PATO adds 2077 new URIs

**Comment by oganm** [comment]
Incidentally, looks like UPHENO works exclusively by importing other files. It would add 118983 new URIs

**Comment by arteymix** [comment]
There's pato-base that we can use which does not import external terms and is pretty slim.

https://obofoundry.org/ontology/pato.html

**Comment by arteymix** [comment]
Ok, done! It will be in the next patch release ;) If you need any of the aforementioned ontologies, feel free to open an issue.
