### ISSUE TITLE
search endpoint broken in dev

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#654]
Neither ontology terms nor plain text seem to return any result

https://gemma.msl.ubc.ca/rest/v2/annotations/human/search/datasets?query=brain (returns results)
https://dev.gemma.msl.ubc.ca/rest/v2/annotations/human/search/datasets?query=brain (doesn't return results)

https://gemma.msl.ubc.ca/rest/v2/annotations/human/search/datasets?query=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000955 (returns results)
https://dev.gemma.msl.ubc.ca/rest/v2/annotations/human/search/datasets?query=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000955 (doesn't return results)

**Comment by arteymix** [comment]
I'll review this after I merged the 1.29.10.

This could be related to the recent merge of the 1.29.9 branch.

**Comment by arteymix** [comment]
Found this in the logs:

```
[Gemma - http-nio-8181-exec-709 (2023-04-18 18:45:09,609)] ERROR ubic.gemma.web.services.rest.providers.AbstractExceptionMapper.toResponse(55) | Unhandled exception was raised for GET /rest/v2/search?query=brain.
ConversionFailedException: Failed to convert from type ubic.gemma.model.genome.biosequence.BioSequence to type ubic.gemma.model.IdentifiableValueObject for value 'BioSequence Id=16356908'; nested exception is java.lang.NullPointerException
org.springframework.core.convert.ConversionFailedException: Failed to convert from type ubic.gemma.model.genome.biosequence.BioSequence to type ubic.gemma.model.IdentifiableValueObject for value 'BioSequence Id=16356908'; nested exception is java.lang.NullPointerException
    at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
    at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:170)
    at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:155)
    at ubic.gemma.core.search.SearchServiceImpl.loadValueObject(SearchServiceImpl.java:294)
```

**Comment by arteymix** [comment]
This is a bug in the VO conversion for genes that we also use in the 1.29. I'll look into it tomorrow.

**Comment by arteymix** [comment]
I marked both sequence and polymer type as nullable.
