### ISSUE TITLE
Auto-suggestion of replacements for obsolete ontology terms

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#656]
Here I document the current ways I have found to replace obsolete terms

- IAO_0100001 component of a class indicates if an element is replaced by another. The record can exist either as a `resource` attribute or text. Grand majority of replacements here are listed as full URIs but I have seen a few cases of short form examples (DOID:12345 instead of http://purl.obolibrary.org/obo/DOID_12345). For these, I look for the obsolete entry in the ontology files and see if it has a listed replacement
    - http://www.ebi.ac.uk/efo/EFO_0000322 -> http://purl.obolibrary.org/obo/CL_0000010 (recorded as text)
    -  http://purl.obolibrary.org/obo/CL_0011107 -> http://purl.obolibrary.org/obo/CL_0000636 (recorded as resource)
    - http://purl.obolibrary.org/obo/MP_0013172 -> MP:0031434 (edge case where a short form is recorded)
- hasAlternativeId component lists alternative IDs as text, always in short form. For these I look to see if any obsolete term is listed as an alternative of another
    - http://purl.obolibrary.org/obo/DOID_0050006 -> http://purl.obolibrary.org/obo/DOID_13250
    - http://purl.obolibrary.org/obo/PATO_000208 -> http://purl.obolibrary.org/obo/PATO_0000694
 - consider: From oboInOwl: "Gives a term which may be an appropriate substitute for an obsolete term, but needs to be looked at carefully by a human expert before the replacement is done" might be useful to come up with recommendations for curators. Seems to be using the short form
     - http://purl.obolibrary.org/obo/GO_0034435 -> GO:0008203

Related to https://github.com/PavlidisLab/GemmaCuration/issues/300

**Comment by ppavlidis** [comment]
This should be implemented as part of findObsoleteTermUsage.

However it seems that we won't want to take up recommended replacements automatically _unless_ they are terms in other ontologies we support. Example: we should use  DO instead of MONDO term suggestions (unless we switch to MONDO).

**Comment by ppavlidis** [comment]
@oganm do you have some specific examples of the different cases? For testing I'd need that, I think we can create some miniature OWL files via protege - so I just need the URIs.

**Comment by oganm** [comment]
Added examples to the post above. still looking in the files to see if I can find more so will update it if i find anything new.

**Comment by ppavlidis** [comment]
Looking at this again it seems like it would definitely take some effort to figure this out and write tests, and it still wouldn't be foolproof.

As long as the number of new obsolete terms we find isn't large, finding the alternatives by hand is not all that onerous.

Because even with these automatic suggestions it feels like checking them by hand is wise, so just letting the obsolete term finder do the replacements might not be desirable.
