### ISSUE TITLE
ACLs can be deleted when entity deletion fails

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#66]
This seems to be a problem with transaction boundaries for entity removal, which has proven hard to reproduce consistently. 

On occasion when deleting an ExpressionExperiment, when this fails (with an exception) the ACLs can be deleted anyway by the interceptor.

Clearly the expected behaviour is that the entire transaction, including the ACL manipulations, should be rolled back.

**Comment by ppavlidis** [comment]
The symptom is that the experiment exists in the system but cannot be retrieved. This is because entities without ALCs are filtered out (this could be changed, but is erring on the safe side to avoid exposing ay sensitive data).

Manually repairing this for an expressionexperiment involves inserting base ACL entries.

> -- ID of the entity
> set @ID=15773;
> 
> -- template for EEs
> 
> select * from ACLOBJECTIDENTITY where OBJECT_CLASS='ubic.gemma.model.expression.experiment.ExpressionExperiment' AND OBJECT_ID=@ID; -- if we get nothing it's a problem
> insert into ACLOBJECTIDENTITY (OBJECT_ID, OBJECT_CLASS, ENTRIES_INHERITING, OWNER_SID_FK, PARENT_OBJECT_FK, OLD_OBJECT_CLASS) VALUES (@ID, "ubic.gemma.model.expression.experiment.ExpressionExperiment", 0, 1, NULL, NULL);
> select @OID := ID from ACLOBJECTIDENTITY WHERE OBJECT_CLASS LIKE "%ExpressionExperiment" and OBJECT_ID=@ID;
> insert into ACLENTRY (GRANTING,MASK,ACE_ORDER,SID_FK,OBJECTIDENTITY_FK) values (1,16,1,1,@OID),(1,1,2,3,@OID),(1,1,3,4,@OID);

**Comment by arteymix** [comment]
Another bug that could explain ACL issue is fixed in 8d772d57ca42cbc041637e615b2326dfe353eb4f. Basically, `ExpressionExperimentService.remove` swallows errors and prevent rollback. If any stage of removing the EE fails, we should rollback, not leave the EE half-deleted.

**Comment by arteymix** [comment]
This is more related to tests, but e510311a05e8e6fee71cab14ecc50e0f2845e845 fixes fixture removal in `DifferentialExpressionAnalyzerServiceTest`. I'm thinking of adding `@After` checks in `BaseSpringContextTest` to ensure that all the fixtures are removed.

**Comment by arteymix** [comment]
I did revisit this in 1.29, and I made some changes in gsec to prevent a new transactions when manipulating ACLs: operations on ACLs should sit in the same transaction as the operation on the underlying entity.

https://github.com/PavlidisLab/gsec/commit/e865dfb77166fa734ac3cb048d5691803f9bdebc

There might be a case for a nested transaction whereas if the ACLs operation fails, only that parts get rolled back and the parent transaction can continue, although it might be preferable to have an error instead.
