### ISSUE TITLE
ReferenceError when selecting brain-related datasetes

### ISSUE THREAD

**Issue by leonfrench** [PavlidisLab/Gemma#68]
I get this error when trying to run a co-expression analysis within the human brain datasets:
"hasCoexpressionAnalysis is not defined ReferenceError: hasCoexpressionAnalysis is not defined"
It looks like it's able to still use 8 datasets, but it would be better if it used the > 100 listed. 

I'm guessing the co-expression analysis might be in progress, so I will try again later. 

![screen shot 2018-08-02 at 6 03 07 pm](https://user-images.githubusercontent.com/1852350/43613709-78dbe260-967e-11e8-81fa-daf1029127a4.png)

**Comment by ppavlidis** [comment]
I'm not able to reproduce this consistently. Can you try again?

**Comment by leonfrench** [comment]
No problem, I just tried again and reproduced it in each of the 3 or so attempts just now. This time I was on a different macbook but got the same error (using Chrome). Another screen shot is attached - that's how it looks before I click on the Purple row with the 121 datasets. I get the same error with firefox (one attempt).

![screen shot 2018-08-02 at 9 53 58 pm](https://user-images.githubusercontent.com/1852350/43620075-fa4d35e0-969e-11e8-846e-ae708de53183.png)

**Comment by ppavlidis** [comment]
I've managed to see it once but not since. Maybe I need to know more exactly how you reproduce it. I 

1. click on the experiment combobox, wait until the list appears. 
2. pick the brain set. 

Chrome and Safari, Mac.

**Comment by leonfrench** [comment]
I just tried it on a Windows machine running IE and saw the same error by doing this:
1. typed 'brain' in experiment combobox
2. clicked on the human brain set that is in purple and has a count of 121 datasets
After that I get the error popup and also it lists 8 of 103 loaded - so maybe the mismatch between those numbers and the 121 may help.

**Comment by ppavlidis** [comment]
Thanks, the combination of typing and selecting a preset was the key. Seems to be okay now.
