### ISSUE TITLE
Highlighting does not seem to work for "cushing"

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#686]
It's important for this query because the "ing" suffix is stemmed and not all results are relevant.

![image](https://github.com/PavlidisLab/Gemma/assets/1318477/5b7dd464-862c-4ea2-993d-fbfef9892418)

**Comment by ppavlidis** [comment]
Thanks. Some of the hits are associated with a paper that has an author with the last name **Cush** (https://pubmed.ncbi.nlm.nih.gov/20725040/) and this is not evident to the user.

**Comment by arteymix** [comment]
Highlighting occurs, but the text is null. I need to debug this.

**Comment by arteymix** [comment]
I figured out yesterday why the highlighted value was null: Compass can return highlights for multiple fields, but picks one arbitrairly if `getHighlightedText()` is used. I added a fix for ignoring null highlights and added support for multiple highlights per search result.

**Comment by arteymix** [comment]
The fix for highlighting is in 54d3e919065e2647ab3416d7e0b048dd9c5cd1ff. The multiple highlights will be in the 1.30 release.
