### ISSUE TITLE
Exception when invalid URLs are rendered to labels

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#690]
Example: https://gemma.msl.ubc.ca/searcher.html?query=http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Organism.owl#birnlex_213

![image](https://github.com/PavlidisLab/Gemma/assets/1318477/a3b21508-910e-4111-b2be-45907d6e9f32)

From https://github.com/PavlidisLab/GemmaCuration/issues/306

**Comment by oganm** [comment]
I have run across this issue as well. It seems to be affecting API endpoints as well. anything with a `#` sign will fail to return a result
