### ISSUE TITLE
Keep the full property path for highlights

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#700]
Currently, a tagged publication title appears as "Tagged title: ...". When the highlights are generated, they are obtained recursively, so there is an opportunity to prepend the full property path. In that case it would be `primaryPublication.title`.

 - [ ] prefix the path when recursing in `CompassSearchSource.processHits`
 - [ ] provide messages for rendering these keys
 - [ ] translate paths into the VO space

This is only meaningful for Gemma REST and GemBrow as we now expose the highlights as a `Map<String, String>`.

**Comment by ppavlidis** [comment]
To be clear we should not expose details of our data model to the end-user of the GUI, but having that information in the client will let us be flexible in how we display it.

For example: "Tag on experiment" rather than ExpressionExperiment etc. Something to fine tune _later_

**Comment by arteymix** [comment]
This is specific for ontology-matched terms, we also need messages for rendering the class names.

Not to get too deep in the details, but there's a neat interface named [MessageSourceResolvable](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/MessageSourceResolvable.html) to pass those messages around and evaluate them in specific context with a MessageSource.

**Comment by arteymix** [comment]
Ok, it's fixed now for classes:

![image](https://github.com/PavlidisLab/Gemma/assets/1318477/6d17e80b-bf6a-4ced-9cb5-32e72195d022)

I'll the the fields in the next release since the current values are OK to render.

**Comment by arteymix** [comment]
This will be addressed in #661

**Comment by arteymix** [comment]
Fixed!
