### ISSUE TITLE
OntologyService.findTerms() method gives unexpected (?) results

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#72]
When querying for "Frontal Cortex" (http://purl.obolibrary.org/obo/UBERON_0001870) using OntologyService.findTerms(), the object returned was a Collection of 4217 OntologyTerm objects. This does not make sense to me.

EDIT: Method call used:
`OntologyService.findTerms('http://purl.obolibrary.org/obo/UBERON_0001870')`

A quick look on a few of the terms include:
Colon mucinous adenocarcinoma (DOID_3029)
increased kidney glutathione level (MP_0012607)

Fortunately, "Frontal Cortex (UBERON_0001870)" is also included in the collection, which means the search is not entirely wrong. However, the UBERON term is used in UBERON, CL, EFO, HP and MP, so I would be expecting 5 instances of this term instead (not one).

EDIT: At most 5 instances, if CL, EFO, HP and MP imports "Frontal Cortex" into their ontology. Having only one means the others didn't do so, which might be just fine.

**Comment by nzllim** [comment]
Closing issue since the input should be free text as opposed to URI. Feeding the URI would result in the search engine matching the parts of the URI to the various ontologies -> Not a bug.

**Comment by ppavlidis** [comment]
We'll add code to detect URIs to avoid this happening inadvertently -- just retrieve the matching term instead of hitting the full-text index.
