### ISSUE TITLE
annotations/search/datasets endpoint broken in dev

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#729]
- https://gemma.msl.ubc.ca/rest/v2/annotations/search/datasets?query=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000955&limit=20&offset=0&sort=%2Bid working fine in production
- https://dev.gemma.msl.ubc.ca/rest/v2/annotations/search/datasets?query=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000955&limit=20&offset=0&sort=%2Bid where are my results in dev

**Comment by oganm** [comment]
Resurgence of https://github.com/PavlidisLab/Gemma/issues/654 it looks like

**Comment by arteymix** [comment]
The query was ignored, it should be fixed in 3ecab10e82f3bd4ba0ac63a939ede96fb84a4e22.

**Comment by arteymix** [comment]
Ok, it should be fixed now.
