### ISSUE TITLE
"s is null TypeError: s is null" when accessing GSE159990.1 as an anonymous user

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#738]
![image](https://github.com/PavlidisLab/Gemma/assets/1318477/e7ce535c-32f1-4330-a29e-db0fb06e689f)

**Comment by arteymix** [comment]
I can't reproduce this bug on in the 1.30 series. This might not be worth fixing.

**Comment by ppavlidis** [comment]
Cannot reproduce in 1.31.6
