### ISSUE TITLE
Merged platforms missing from getGeneProbes endpoint

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#742]
`getGeneProbes` endpoint will return a list of probesets and platforms for a given gene. However this output list does not include artificial platforms we have created by merging platforms. This is likely working as intended but we might consider changing the intention here since some use cases would involve being able to access artificial platform information too.

For instance, accessing all datasets where a particular gene can be observed. My expected workflow would be to do `getGeneProbes` to get all platforms then to use `getPlatformDatasets` to get all the datasets using those platforms. Using this approach however doesn't let me connect, say [TSPY10](https://gemma.msl.ubc.ca/gene/showGene.html?id=8095074) and [GSE3500](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=740) since the [platform it uses](https://gemma.msl.ubc.ca/arrays/showArrayDesign.html?id=270) is merged from [another one](https://gemma.msl.ubc.ca/arrays/showArrayDesign.html?id=182).

An alternative way to connect these two would be if the `getPlatformsByIds` endpoint returned this merge information

**Comment by oganm** [comment]
Can also see them missing in the [page for the gene](https://gemma.msl.ubc.ca/gene/showGene.html?id=8095074). The merged platforms such as [SH-HL
](https://gemma.msl.ubc.ca/arrays/showArrayDesign.html?id=270) isn't present on the list

**Comment by ppavlidis** [comment]
Definitely a bug IMO, thanks

**Comment by arteymix** [comment]
I'll add the code for initializing them. The VOs are designed to ignore relations that haven't been initialized.

**Comment by arteymix** [comment]
To be clear, merged platforms appear in the endpoint output, but the VOs are not filled. I'm almost done!
