### ISSUE TITLE
Web search for Phenotypes fails

### ISSUE THREAD

**Issue by fratajcz** [PavlidisLab/Gemma#746]
Hi!

I have previously used the phenotypes interface to obtain lists differentially expressed genes for individual HPO terms. However, the interface stopped working in the meantime, so when I go to `https://gemma.msl.ubc.ca/phenotypes.html`, a popup appears with the following text and the HPO browser on the left remains unpopulated:

```
Error during read
java.lang.RuntimeException:
Message: Ontologies are not fully loaded yet, try again soon
Details:
ubic.gemma.core.association.phenotype.PhenotypeAssociationManagerServiceImpl.findAllPhenotypesByTree (1668)
ubic.gemma.core.association.phenotype.PhenotypeAssociationManagerServiceImpl.loadAllPhenotypesByTree (488)
sun.reflect.DelegatingMethodAccessorImpl.invoke (43)
java.lang.reflect.Method.invoke (498)
org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection (317)
org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint (183)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed (150)
org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke (91)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed (172)
org.springframework.aop.framework.JdkDynamicAopProxy.invoke (204)
ubic.gemma.web.controller.PhenotypeController.loadAllPhenotypesByTree (146)
sun.reflect.DelegatingMethodAccessorImpl.invoke (43)
java.lang.reflect.Method.invoke (498)
org.directwebremoting.impl.ExecuteAjaxFilter.doFilter (34)
org.directwebremoting.impl.DefaultRemoter$1.doFilter (428)
org.directwebremoting.impl.DefaultRemoter.execute (431)
org.directwebremoting.impl.DefaultRemoter.execute (283)
org.directwebremoting.servlet.PlainCallHandler.handle (52)
... (truncated)
```

Would be great if the phenotype browser is kept alive, I found it tremendously useful!

**Comment by fratajcz** [comment]
Ah, thats too bad! Is there another way to achieve the same result with Gemma, i.e. answering the question "What are the differentially expressed genes for phenotype XYZ?" ?

**Comment by arteymix** [comment]
We have recently replaced our usage of the Disease Ontology with MONDO which Phenocarta relied upon for listing disease-associated genes. The good news is that we will restore the functionality in the next patch release, but Phenocarta remains outdated.

Phenocarta does not answer the question you are asking. The evidence for gene-disease association is not coming from our trove of differential expression data, but rather external sources (i.e. publications, GWAS studies, etc.)

**Comment by arteymix** [comment]
The functionality is fully restored. We transitioned all the DO terms to MONDO.
