### ISSUE TITLE
[Refactor] Consistent Implementation of getTerm() and isOntologyLoaded() methods for GeneOntologyService

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#76]
Unlike other other ontology services (with the exception of Gemma Ontology), GeneOntologyService is implemented outside of baseCode.

To improve coding consistency, I suggest implementing both the getTerm() and isOntologyLoaded() methods.
1. getTerm() or any possible derivative is NOT implemented in the current GeneOntologyService.
2. isOntologyLoaded() is currently called `isGeneOntologyLoaded()`. Renaming the method call might be a good idea.

**Comment by ppavlidis** [comment]
This is because it doesn't extend the same superclass as the other services; it's historical and I agree it would be good to unify, but it's probably nontrivial (for little gain). Maybe you need to clarify how big of an issue this is for you.

The isGeneOntologyLoaded method doesn't need to be there and I may remove it; the correct method to use is isReady.

**Comment by nzllim** [comment]
In one of my scripts, I'm keeping track of the source of ontology terms (and its ancestors), and this requires the use of finding exact matches of the terms in every ontology model via getTerm(). Currently, I am able to perform this for all other ontologies within a loop that calls getTerm(), and I'm excluding GO-inferencing (due to the lack of this method call).

*Context: I used to perform ontology inference manually using OBO files in R, but I'm looking to migrate out from that system over to that already supported in Gemma, since I've finally figured out how to get them to work nicely in CLI+Jython.

**Comment by nzllim** [comment]
Instead of rewriting GeneOntologyService to fit its theoretical superclass, a cut-and-paste implementation of getTerm() can be migrated into GeneOntologyService (if possible) and that would address my need nicely. (A major refactor could be done in the less immediate future once we do have spare developer time).

**Comment by ppavlidis** [comment]
If you only need getTerm then yes that's doable.
