### ISSUE TITLE
Inclusion of measurements in factor value VOs

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#761]
Measurement details are not included within the factor information that is returned

https://dev.gemma.msl.ubc.ca/rest/v2/datasets/GSE5389/analyses/differential

- [ ] omit `characteristics` for continuous factors (only if mutually exclusive)
- [ ] omit `measurement` for categorical factors
- [ ] include `isMeasurement` in `FactorValueBasicValueObject`

**Comment by arteymix** [comment]
![image](https://github.com/PavlidisLab/Gemma/assets/1318477/f66bdf5e-c1f9-41d0-b729-9f31c6bb7f95)
