### ISSUE TITLE
search fails to locate CHEBI compound by name

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#772]
In this experiment that I stumbled across https://gemma.msl.ubc.ca/experimentalDesign/showExperimentalDesign.html?eeid=25186

I noticed that SKF-82958 is annotated using free text. This compound is in CHEBI:

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:111172

(I figured this out via https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL35354/; unfortunately, CHEBI doesn't record the SKF-82958 synonym)

However, in the experimental design editor Gemma fails to locate this compound when searching by its full name `9-chloro-5-phenyl-3-prop-2-enyl-1,2,4,5-tetrahydro-3-benzazepine-7,8-diol`

<img width="522" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/5c96e3bc-82b1-4ae6-8e25-3d901a09ee5c">

There seems no other viable way to locate it (I also tried http://purl.obolibrary.org/obo/CHEBI_111172). 

Searching for just the prefix `9-chloro` does not yield useful results (they don't seem to match this string at all). 

<img width="498" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/0b9a6828-7301-45f6-a84e-cedbd570aeb1">

* Obviously searching by exact name should work; maybe this name is a problem for the query parser. As a fallback, searching by URI should also work.
* If the search doesn't find any good matches, I'm not sure it is helpful to show all those irrelevant ones. I don't know if this can be detected. It's not a big deal but if these *are* high-scoring results, something more serious is wrong. It's been discussed before, but when a curator is searching for a specific term, the results really have to match the string they put in at least partly. I can't fathom why these GO terms are coming up as the best matches, followed by a bunch of random genes (not shown in my screenshot) - no actual CHEBI terms are returned at all so far as I can see, certainly not high on the list.

**Comment by arteymix** [comment]
The "-" character is used to remove term from the full-text match. Have you tried quoting the compound name?

**Comment by arteymix** [comment]
Another thing I can look into is which attributes we have whitelisted in baseCode for indexing. There might be extra things that ChEBI uses that we should include there.

I'll also see if I can make this specific to each ontology.

**Comment by ppavlidis** [comment]
Searching by the quoted name doesn't work either. It yields irrelevant results.

Should searching by URI work in that interface? That would at least be a work-around.

Since CHEBi apparently doesn't record the synonym SKF-82958, adding more fields from the ontology presumably won't help

**Comment by arteymix** [comment]
It is the first result that comes up on the dev server:

![image](https://github.com/PavlidisLab/Gemma/assets/1318477/91ed6564-4661-4673-889d-281a98649937)

I've written some unit tests to confirm that the query is properly passed.

**Comment by arteymix** [comment]
Test added in 155eb33eaba31128e71c6356d6e1da970adf0db7.

I also wrote a test for chebi, but the ontology is too big to be included.
