### ISSUE TITLE
Empty queries return empty results

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#783]
[getDatasets](https://dev.gemma.msl.ubc.ca/resources/restapidocs/index.html#/default/getDatasets) enpoint returns empty result when an empty query is provided. I am unsure if this is intentional since in the production version empty queries are ignored.

- Returns all datasets: https://gemma.msl.ubc.ca/rest/v2/datasets?query=
- Returns no datasets: https://dev.gemma.msl.ubc.ca/rest/v2/datasets?query=

This change causes a bit of inconvenience in gemma.R that I can work around but would prefer to know if it's here to stay before doing anything about it

**Comment by arteymix** [comment]
Yup, empty query should be simply ignored.

**Comment by arteymix** [comment]
Oh, `query` does not exist in the 1.29 series, so it's not really a regression.

**Comment by arteymix** [comment]
https://dev.gemma.msl.ubc.ca/rest/v2/search?query= returns an error. We'll replicate the same behaviour.
