### ISSUE TITLE
Geeq components of getDatasets endpoint sporadically return all nulls

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#812]
I am yet to find a way to reliably replicate this but it seems like the getDatasets endpoint doesn't like populating geeq consistently. I have tried the base endpoint along with a few filters, all of which seem to only occasionally return with non-null geeq fields

https://gemma.msl.ubc.ca/rest/v2/datasets/

**Comment by oganm** [comment]
Accession field is also set to null then this happens

**Comment by arteymix** [comment]
This is caused by the query caching. Relations obtained from the cache are not being initialized, so we have to do some manual work.

Turns out I was overriding the default for EE to incorporate ACL information in the VO and it was missing the initialization code.
