### ISSUE TITLE
reduce significant digits in data outputs

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#813]
The expression data profile files we provide via the web interface give expression values with too many digits, like

6.171141897500001

This should be presented with maybe 4 digits after the decimal. That's more than enough.

It has a pretty big effect on file size, and also it's fake precision - it's not like we know the measured expression level of a gene to one part in a trillion.

**Comment by arteymix** [comment]
This is the format we use for the REST API:

![image](https://github.com/PavlidisLab/Gemma/assets/1318477/f42802f2-1b12-414f-8bee-fd29842752f9)

**Comment by arteymix** [comment]
It's possible that on-disk files are still using the older format. Let me look into that.

**Comment by ppavlidis** [comment]
That's fine, though gotta say 7.161E-1 is a lot harder to read than 0.7161. Obviously for p-values it's a bit different than expression values and human readability of the file isn't too important. Anyway, third-party software (e..g R) should read this in just fine which is most important.

**Comment by ppavlidis** [comment]
> It's possible that on-disk files are still using the older format. Let me look into that.

I wouldn't bother trying to fix old files. It's not wrong to have all those digits, it's just unnecessary

**Comment by arteymix** [comment]
Yeah, we might have to use a different format if the number is greater than one to show all the leading digits.

**Comment by arteymix** [comment]
Follow up in #839 for the decimal places formatting.
