### ISSUE TITLE
repeated gene instances in UI visualization "edit selection"

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#815]
https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE48979

Visualization tab: search for EZH2, select it, visualize.

Click on "Edit selection"   

<img width="770" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/7b024bae-49a0-4e61-9be0-ea283368362d">

search for and add "SP1". Close the window.

Closing this then updates the UI to show 

<img width="309" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/267baddc-04e8-4bc5-8d5b-195c821c07f0">

But this fails to show SP1.

In contrast doing SP1 separately shows there is data for it.

**Comment by arteymix** [comment]
Looks like a missing distinct/group by in the SQL query.
