### ISSUE TITLE
Add link to new browser in the 'explore' menu

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#819]
<img width="237" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/865c5f8a-75ad-4a63-9c28-4b3267932a26">

Maybe it should say "Browse data (legacy)" for the old one?

(The new interface isn't yet a complete replacement for the old one. I still like the old one sometimes because of the extra information shown in the table for admins like GEEQ and DEA status, and the 'what's new' of course, but I think we decided that should just be on the home page)

**Comment by arteymix** [comment]
I'm adding a new menu item to access the legacy browse datasets until we fully reimplement the features.

**Comment by arteymix** [comment]
Fixed in c08a0a415e64c9113e563385e012f63e77cc66ed
