### ISSUE TITLE
Missing Platform Mapping for GPL17692

### ISSUE THREAD

**Issue by owentsai** [PavlidisLab/Gemma#83]
Line In Question: https://github.com/PavlidisLab/Gemma/blob/800a52b48c6764c90ca33528507fdd5414e7264a/gemma-core/src/main/resources/ubic/gemma/core/loader/affy.celmappings.properties#L34

To Append (NOT REPLACE):
HuGene-2_1-st=GPL17692

~Also, CDF file needs to be added (currently not available on Gemma).~

**Comment by nzllim** [comment]
The MPS file is currently non-accessible at the ThermoFisher (current owner of Affymetrix) website. I've written in asking about the file link.
