### ISSUE TITLE
Gemma propagation doesn't recognise substantia nigra as part of the brain and 

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#842]
When using the term for brain (http://purl.obolibrary.org/obo/UBERON_000095) to fetch datasets from all brain regions, the propagation seems to be missing a few terms, most but not all of the missing items can be explained with missing terms in the propagated filter term the endpoint returns

Attempted query: https://gemma.msl.ubc.ca/rest/v2/datasets/?filter=allCharacteristics.valueUri%20%3D%20http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000955

Missing results that should have been in there

- GSE8397: https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=873
    -  This dataset is annotated with various substantia related termsUBERON_0001965, UBERON_0002661, UBERON_0001966. None of these appear in the returned filter despite being part of brain as also supported by the ontology
- GSE166024: https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=18019
    - has UBERON_0001965 (substantia nigra pars compacta)
- GSE206308.2: https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=25992
    - has UBERON_0001965 (substantia nigra pars compacta)
- GSE168496:  https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=26791
    - has UBERON_0002038 (substantia nigra). This term is also missing from the propagated filter
- GSE161045: https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=27018
    - this one is an outlier because it is annotated with UBERON_0001874 (putamen) and this term does appear in the returned filter. I have no idea why the dataset is left behind

**Comment by ppavlidis** [comment]
Thanks for pointing this out. Substantia nigra () should definitely be included in "brain" as it is a child term.

<img width="450" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/45914359-05b4-43f9-a2a1-68a416ee0578">

But for GSE161045, [UBERON_0002038](http://purl.obolibrary.org/obo/UBERON_0002038) is not putamen, it's substantia nigra.

**Comment by oganm** [comment]
Yep. Pasted the wrong term. It is UBERON_0001874

**Comment by arteymix** [comment]
The inference is working as expected:

![image](https://github.com/PavlidisLab/Gemma/assets/1318477/ba7d723f-455c-4a40-841f-d869960c1c85)

Is it possible that a free-term is used in the dataset?

**Comment by ppavlidis** [comment]
> The inference is working as expected:
> 
> ![image](https://user-images.githubusercontent.com/1318477/268361654-5dec0ff6-09b2-40aa-9594-eb7854ceb076.png)
> 
> Is it possible that a free-term is used in the dataset?

Not for the examples Ogan gave. They are annotated with an ontology term that is a subclass of Brain.

<img width="673" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/9bd302e4-55c9-4c50-bb2d-45d1bec546af">

**Comment by ppavlidis** [comment]
Confirmation in the Browser that something isn't working right, directly searching for a dataset mentioned while having "brain" checked yields:

<img width="905" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/6e32e21d-c7eb-416a-9c23-22afd2164837">

**Comment by oganm** [comment]
The annotations do appear to be ontology terms and not free text but UBERON_0002038 does appear in the propagated filter despite missing the dataset annotated with it, similar to the putamen term. UBERON_0001965, UBERON_0002661 and UBERON_0001966 however do not appear in the propagated filter at all

**Comment by arteymix** [comment]
Ok, [substantia nigra](http://purl.obolibrary.org/obo/UBERON_0002038) is inferred, but not [substantia nigra pars compacta](http://purl.obolibrary.org/obo/UBERON_0001965) which is a children as per the "part of" relation. I'll debug that...

**Comment by oganm** [comment]
just to make sure, while substantia nigra *is* inferred, the dataset annotated with it still isn't within the results

**Comment by arteymix** [comment]
It looks like a bug in the inference code. I can reproduce this.

With Uberon base OWL, I get none of the terms and regular Uberon only returns "substantia nigra"

**Comment by arteymix** [comment]
This could be due to the fact we're only using the transitive inference instead of the full OWL inference.

**Comment by arteymix** [comment]
Yeah, it looks like we need at least the mini OWL inference to capture "part of" relations:

![image](https://github.com/PavlidisLab/Gemma/assets/1318477/495b73a7-43eb-4c66-8208-a2fd5be918a0)

**Comment by arteymix** [comment]
I'll try using the micro OWL instead of the transitive inference.

**Comment by arteymix** [comment]
I did some additional tests and it turns out that for our version of Jena, inference with `owl:someValuesFrom` is only support for the full reasoner.

I've introduced a workaround in baseCode to revisit parents/children that might have been missed to to limited inference capabilities. https://github.com/PavlidisLab/baseCode/pull/37/commits/09d7b20a76101c8835cc8d2b01e9aca7d23a8946

We won't need to use a newer version of Jena for now as per https://github.com/PavlidisLab/baseCode/pull/36.

I'll push the fix on the development branch for testing.

**Comment by oganm** [comment]
None of the examples above are returned with the 'allCharacteristics.valueUri = http://purl.obolibrary.org/obo/UBERON_0000955' in the development version as of now

**Comment by arteymix** [comment]
I see! The tag is on the sample itself, but we only index the FactorValue of the BioMaterial. This is utterly useless because those factors are already declared in the experimental design which we add separately.

**Comment by arteymix** [comment]
Fully fixed in 570a7c6362cc9aba7e4d3515b0cc17a645d86843
