### ISSUE TITLE
Informative response when querying experiments that are not available on Gemma, that also uses blacklisted platforms

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#86]
Since the blacklisting mechanism is now available both at the experiment and platform level, one potential use case is when a user searches for an experiment in Gemma, but that experiment does not exist because it uses a blacklisted platform (and as such cannot be loaded into Gemma).

Gemma could do a quick search for the GEO experiment, and identify that it uses a blacklisted platform and respond accordingly (e.g. "This experiment does not exist as it uses a blacklisted platform; the platform is blacklisted because ..."). A potential drawback for implementing this mechanism on the search engine would be a huge increase in calls to GEO (especially if the query statement is incorrect, i.e. bad GSE ID), and would likely slow down future searches also. Pre-emptive caching of such experiments could reduce the GEO query burden.

Potential Test Case: GSE32554

**Comment by ppavlidis** [comment]
Rather than doing this (since we are rarely asked about data we lack) we should just make it clear to users that there are multiple reasons we might not have a dataset.

**Comment by arteymix** [comment]
The search displays datasets and platforms that are blacklisted.
