### ISSUE TITLE
Searching for "brain" experiments returns error

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#87]
Steps to reproduce:
1. Search for "brain", constraint search for experiments.

Gemma returns an error: "Error during read [object Object]".

**Comment by nzllim** [comment]
UPDATE:
1. Searching with "liver", "lung", "heart", "astrocyte" or "microglial" does not return the same error (experiments are listed as should).
2. Searching with "cancer", "tumor" or "tumour" reproduces the error.

Could the size of the results (e.g. more than 1000 experiments?) be the cause of the error?

**Comment by ppavlidis** [comment]
it looks like it just is timing out, so it is likely related to the size of the results. That error message you see in the client is generic (we should handle it better) and you can see the actual response in the browser developer tools

**Comment by ppavlidis** [comment]
I am tentatively closing this issue as we were able to get performance up to a good level (esp once caches are warmed up).
