### ISSUE TITLE
UI looks broken when opening the link of a deleted experiement 

### ISSUE THREAD

**Issue by Mahanrn** [PavlidisLab/Gemma#874]
[GSE228390](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE228390) This was deleted by me. If you now open the link it shows `Unable to access experiment with shortName=GSE228390` and many lines of code below it. This doesn't affect functionality at all, but I think it can look better. 

Maybe not worth the trouble at all (or already pointed out?) --- feel free to close the issue if that's the case. 

![image](https://github.com/PavlidisLab/Gemma/assets/117854412/43dabcff-1ea4-4277-9d8a-ff23e62aac4a)

**Comment by ppavlidis** [comment]
I'm not sure (you can check) but the stack trace is only shown if you are an administrator?

**Comment by Mahanrn** [comment]
Ahh yes..... I checked. Thanks Paul.
