### ISSUE TITLE
Create a dummy class of gene products and sequences for generic platforms

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#886]
The way we make gene-level generic platforms (used for RNAseq) is very hacky. Our data model requires that elements on platforms be associated indirectly to genes via a sequence and a gene product (transcript). We use "real" sequences and transcripts to do this, which is messy. For one thing, it can be confusing when this is exposed because the specific transcript/sequence is not relevant (the data we import is just at the gene level) - we choose the transcript arbitrarily and that comes with the sequence we use.  Second, it raises a concern about how we handle if a transcript is removed from a gene by NCBI - so it's a possible source of bugs (we need to check but there have been some strange things in generic platforms like "unmapped" elements).

A solution would be to give each gene a "dummy" transcript and sequence that merely provide the required link in our model, but transmits no other information. These would be "permanent" (over the lifetime of the gene in the system) and thus not subject to any fiddling when we update NCBI information (unless a gene is added or deleted).

Tasks:
- [x] Implement subclasses of GeneProduct and BioSequence, most likely, to play this role.
- [x] Add code to create new dummies when a new gene is created, and delete them if a gene is deleted.
- [x] Backfill these entities for existing genes
- [x] Ensure these dummies are filtered out from places where we are intending to show the transcript and sequences - the dummies should be basically invisible.

**Comment by arteymix** [comment]
An alternative would be to flag one gene product as representative and require that it is never being removed unless properly replaced by another representative gene product.
