### ISSUE TITLE
"Other Parts" doesn't display all splits

### ISSUE THREAD

**Issue by Mahanrn** [PavlidisLab/Gemma#898]
For example, [GSE111696.1](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE111696.1), has 2 other splits, but the 3rd split isn't shown. 
[GSE111696.2](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE111696.2) The second split  only shows the ".1" split, but not the ".3".
[GSE111696.3](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE111696.3) The third part only shows the first part.

**Comment by arteymix** [comment]
@Mahanrn Do you recall any error when you performed the split yesterday?

**Comment by Mahanrn** [comment]
No, no errors. All of the splits are fine, they are just not shown in that section.

**Comment by arteymix** [comment]
I looked up the database and the relations appear to be missing.

The code in `SplitExpressionExperiment` is doing the right thing though.

**Comment by arteymix** [comment]
The database has the correct splits:
![image](https://github.com/PavlidisLab/Gemma/assets/1318477/ce6d0702-9aab-47e1-b128-a770bac87841)

Thus this is not a bug in the split experiment logic. I'll review how we render it.

**Comment by arteymix** [comment]
The query was lacking a group by on the other part so only the first part found was picked up.
