### ISSUE TITLE
Error while indexing in Hibernate Search

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#904]
[Gemma - pool-280-thread-15 (2023-10-13 10:46:20,191)] ERROR ubic.gemma.core.job.executor.webapp.TaskRunningServiceImpl$1.onFailure(94) | org.springframework.orm.hibernate4.HibernateSystemException: Error while indexing in Hibernate Search (before transaction completion); nested exception is org.hibernate.HibernateException: Error while indexing in Hibernate Search (before transaction completion)

https://pavlidis-lab.slack.com/archives/C02LZHP6RB3/p1697219180389559

**Comment by ppavlidis** [comment]
I thought we had migrated away from Hibernate search entirely, so is this still relevant?

**Comment by arteymix** [comment]
We've migrated from Compass to Hibernate Search. This is still relevant.

The issue hasn't come up since then, so I'll just close it.
