### ISSUE TITLE
curator interface doesn't show all biomaterial characteristics in the sample table

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#908]
There's probably  a simple reason for this, but in the sample-level view, we only list certain 'raw characteristics'. I don't know why we don't show them all.

Compare https://gemma.msl.ubc.ca/experimentalDesign/showExperimentalDesign.html?eeid=23636

<img width="399" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/5b575ba1-eaba-4927-a85a-effa045c508b">

 to https://gemma.msl.ubc.ca/bioMaterial/showBioMaterial.html?id=711142 

<img width="574" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/65feaadd-faeb-45d3-b9f7-cae22c5db8c4">

There was apparently some problem with our parsing of this GEO data set's annotations which could be leading to them being filtered out of the display, but that's not the main point as I've seen this elsewhere; I just need to review the rules we use to include/exclude things for display and be more liberal.

**Comment by ppavlidis** [comment]
The reason we can't display those is there are multiple items that have no category, and there is no way to associate them together across biomaterials, as it is ambigous.

This shouldn't really happen as much as it does, though, but there is a defect in our initial parsing of the GEO SOFT files (it seemed better before, but some kind of cleanup might have made it worse, probably my fault).

If a sample characteristic (which becomes a Biomaterial characteristic, not a factor-value characteristic) doesn't have a recognizable "category" like "age", we end up leaving the category blank, rather than filling something in. But we keep the value. This means we can't always tell what the value was, but it also means we don't display it. We also are not saving the "original value" correctly (we were, at one point). We also expect the categories to be unique in the experiment (at least, among the biomaterial characteristics).

Just to explain where this comes from, usually the GEO SOFT file has a category like (in this case) (example of GEO context [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3529120))

```
!Sample_characteristics_ch1 = sequencing metric pc1: 0.068139237
!Sample_characteristics_ch1 = sequencing metric pc2: -0.035139329
!Sample_characteristics_ch1 = sequencing metric pc3: -0.068505948
!Sample_characteristics_ch1 = b.cells.naive: 0.0296384521445652
!Sample_characteristics_ch1 = b.cells.memory: 0
!Sample_characteristics_ch1 = plasma.cells: 0.00167691800681738
!Sample_characteristics_ch1 = t.cells.cd8: 0.0275197069817969
```

But they aren't one of our recognized categories, and our data model doesn't have a way to track them. But in many cases, we do store the entire string like "plasma.cells: 0.00167691800681738" as the characteristic.value and/or as the originalValue (but this was not working right). See for example [here](https://gemma.msl.ubc.ca/bioMaterial/showBioMaterial.html?id=16977) (and almost a million biomaterial characteristics lacking a category have a ':' in it; there's just another 500k that don't have that, which are the problems)

When we parse, we can't use a category like "Other" because there would be multiple values for each biomaterial that has that category and no way to associate any of them as belonging "together" (as mentioned above).

But there was also an issue with dropping some usable data from the sample display, which I am addressing.

Furthermore, for these datasets that have a load of biomaterial characteristics with no category, making it ambiguous what they mean, there is really no way to repair them short of reloading the information from the SOFT files. They may need to be deleted.

In the ExperimentalDesignController (which chooses what to display) we use the value before the first : or = as the "category". This doesn't really work right when the string is something like "Gender: male, Age: 19 days Diet: Ad lib" (which happens a lot in GEO)  - we currently try to split those up though in the GeoConverter, but if that doesn't work it's not a big deal.

At the moment: I changed so that GeoConverter always keeps the raw string in the "original value" for characteristics, and when we "fall back" in the face of no category being identified, we use the "category" from GEO. This at least protects us from data loss of the GEO "category" like "t.cells.cd8".

**Comment by arteymix** [comment]
If we parse this category and fill it in the biomaterial, it will be populated in the EE2C table and subsequently visible from the REST API. We need to coordinate this with a patch so that those categories can be excluded from the API.

We don't have any free-text categories presently, so it might make sense to exclude those altogether.

**Comment by ppavlidis** [comment]
With this and #911 implemented, we could (carefully) migrate a lot (~1M) of existing null-Category characteristics into free text Categories and cleaner free text Values by splitting the existing Value on the ":" (or "=") that GEO SOFT uses as a delimiter and which our older parsers didn't try to handle. (this actually occurs in quite a few other values even when the category is not null, but like 20k).

Again, the main reason to do this is so we can display them more nicely to curators as the basis for experimental designs, so this isn't *that* important for old datasets (vs new ones we are curating)

**Comment by arteymix** [comment]
I filed the backfilling task in the curation repository, so there's nothing left to do here.
