### ISSUE TITLE
Missing MPS settings for GPL23126

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#91]
Problem: as title; affy.mps.properties needs to be populated accordingly

~The link to the file is currently down, I have just contacted ThermoFisher Tech Support. Will update again once the link is live.~ Link is live (download failed due to browser issues).

File can be downloaded here ~(currently unresolvable)~:
https://sec-assets.thermofisher.com/TFS-Assets/LSG/Support-Files/Clariom_D_Human_Analysis-r1.zip

**Comment by ppavlidis** [comment]
The config has been updated, making a mild assumption about the file names. Will leave this open until confirmation.

**Comment by nzllim** [comment]
MPS files uploaded to the server, no further name change necessary - Issue closed.
