### ISSUE TITLE
Account for statement-style descriptions of baselines for DEA

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#918]
The code that tries to guess which factorvalue is to be used as a baseline needs to look in the entire statement, as going forward, "control" will often be the object to a "has_role" predicate. Though there may be other possibilieis, and also any currently supported patterns will still be considered valid (e.g. if "control" is used in isolation)

We can look at the curation to see specific examples of the patterns that are going to be occurring.

**Comment by arteymix** [comment]
What I can do to keep it backward compatible during the transition is to lookup old-style characteristics as a fallback with the current logic.
