### ISSUE TITLE
NCBI GEO FTP address change (breaks addGeoData)

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#93]
The FTP link for GEO has changed, it is now more convoluted than before.

Previously: ftp://ftp.ncbi.nlm.nih.gov/pub/geo/DATA/SOFT/by_series/GSE56785/GSE93295_family.soft.gz

Now: ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE56nnn/GSE56785/soft/GSE56785_family.soft.gz

Note that the series is nested in a directory branch (i.e. GSE56nnn), of which is generated by replacing the right-most three numbers with "nnn".

**Comment by ppavlidis** [comment]
Well that explains why some tests were failing. In the past that has always been due to network glitchiness so I kind of ignored them, my bad. Easy to fix. Next patch release unless urgency high, let me know offline
