### ISSUE TITLE
Support additional FASTQ headers for batch information extraction

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#97]
I have a couple of cases of batch information with non-standard FASTQ headers with 3, 6, 8 or 9 fields. Are those handled by Gemma?

There are cases of FASTQ headers separated by underscores `_` instead of `:` characters.

There's also cases of partial batch information where only a subset of samples has proper FASTQ headers and the rest are unusable. It might be reasonable to discard those.

The last case is single lane batch information. It would be great if the submission of such batch information would succeed and tag the experiment as single lane. I'm currently checking for the existence of a batch factor to determine if a dataset has been already submitted, but if we can have a tag specifically for that, I would also add a case in the completion logic.

The single lane case is critical because it applies to a very substantial fraction of the datasets processed so far. It's not fair to penalize the GEEQ score of experiments that have a single batch factor.

**Comment by ppavlidis** [comment]
Sorry I didn't see this earlier (assign things to me to help ensure they reach me), but offline you can send me some examples. We handle a number of variant headers, but more can be added, if we are suitably motivated (i.e, it's not just one experiment - in such cases, manually adding the batch factor could be better)

When we have only partial batch information we generally just fail to add the batch information. If we know that the "unusable" ones essentially represent a different batch, we could do that, but generally we don't know what the story is, so we consider it unusable.

About the single-lane case, the system already handles that case: that there are no batches. But if something isn't working right file a bug.

**Comment by arteymix** [comment]
Here's a list of GSE that have unsupported batch info formats:

 - GSE55790
 - GSE35584
 - GSE60101
 - GSE56292
 - GSE51827
 - GSE49321.1
 - GSE49379.3
 - GSE30017.2
 - GSE22068.2
 - GSE44875.2

You can preview them under https://home.pavlab.msl.ubc.ca/rnaseq-pipeline/experiment/{ee.shortName}, for example https://home.pavlab.msl.ubc.ca/rnaseq-pipeline/experiment/GSE55790

If we prefer not to support this, I'll just mark those as unrecoverable.

**Comment by ppavlidis** [comment]
Can you add examples of the headers here? It's a pain to have to get on the vpn just to see what you are talking about. Thanks!

**Comment by arteymix** [comment]
[GSE55790.fastq-headers-table.txt](https://github.com/PavlidisLab/Gemma/files/6718860/GSE55790.fastq-headers-table.txt)
[GSE35584.fastq-headers-table.txt](https://github.com/PavlidisLab/Gemma/files/6718867/GSE35584.fastq-headers-table.txt)
[GSE60101.fastq-headers-table.txt](https://github.com/PavlidisLab/Gemma/files/6718871/GSE60101.fastq-headers-table.txt)
[GSE56292.fastq-headers-table.txt](https://github.com/PavlidisLab/Gemma/files/6718873/GSE56292.fastq-headers-table.txt)
[GSE51827.fastq-headers-table.txt](https://github.com/PavlidisLab/Gemma/files/6718876/GSE51827.fastq-headers-table.txt)

**Comment by arteymix** [comment]
List of all supported format on SRA: https://www.ncbi.nlm.nih.gov/sra/docs/submitformats/. Some examples above don't meet the accepted formats, and we should decide what to do about them. It also lists formats for other platforms.

Here's the Illumina ones:

Recent:

```
@<instrument>:<run number>:<flowcell ID>:<lane>:<tile>:<xpos>:<y-pos> <read>:<is filtered>:<control number>:<index>
```

This format is documented here: https://help.basespace.illumina.com/articles/descriptive/fastq-files/

Older:
```
@<machine_id>:<lane>:<tile>:<x_coord>:<y_coord>#<index>/<read>
```

Native illumina (legacy)

```
<flowcell> = [a-zA-Z0-9_-]{2}+
       <lane> = 1..8
       <title> = 1..1024
            <X> = 1..4096
            <Y> = 1..4096
<sep> ::= [_\t]
READNAME ::= [<flowcell><sep> | s_]<lane><sep><tile><sep><x><sep><y>
```

We're clearly not supporting this one, and I have multiple examples of datasets using underscores as separator in the RNA-Seq pipeline queue.

**Comment by ppavlidis** [comment]
Thanks. The thing to do is to make each (distinct) example into a test, and then update the parser until the tests pass (there is a pattern of tests already so that's easy). I will do this if I get a chance.

**Comment by ppavlidis** [comment]
Just to make sure:

HW-ST997_0144_6_1101_1138_2179 ->
 - HW-ST997 = device
 - 0144 = flowcell
 - 6 = lane

This has 6 fields, which I can't find listed among the formats, but if my parse is correct it's okay.

Then there is one like
1_40_501
What are these three fields? 

That NCBI page seems incomplete, or I'm just missing something.

**Comment by ppavlidis** [comment]
I'm thinking those three fields are not useful, and at least for this experiment it's not usable for batching. As you can see, the values for the first field are all 1, the second field has only mild clustering of values with several singletons, and the third appear unique to each sample. But if it's a valid format we can support it.

![image](https://user-images.githubusercontent.com/206415/124524591-8036f500-ddb0-11eb-9a04-c88b2d8d6b87.png)

**Comment by arteymix** [comment]
Just reporting here a discussion with @ppavlidis 

I looked at the data we have to see how samples uses ":" and "_" to separate batch information.

The ":" separator is mainly focused around 5 and 7 fields, both of which are already documented:

![image](https://user-images.githubusercontent.com/1318477/124646014-fa1abd00-de48-11eb-80df-4bba679ec210.png)

The 5 and 7 fields separated by ":" cover 91% of the cases with batch information.

At first, the "_" appeared to be used in a broad range of field numbers:

![image](https://user-images.githubusercontent.com/1318477/124646195-30583c80-de49-11eb-960c-6c210ca565eb.png)

However, upon excluding 5 and 7 ":" fields, we have a much clearer picture:

![image](https://user-images.githubusercontent.com/1318477/124646291-4fef6500-de49-11eb-9595-b87d65e66a1a.png)

The 5 fields separated by underscores cover 2.4% of the cases with batch information.

This is due to some devices using underscores as separator and thus conflating with underscore separators.

Conclusion: by handling 5 and 7 fields separated by ":" and then looking for 5 fields separated by "_", we can cover the great majority of cases out there.

**Comment by ppavlidis** [comment]
GSE111979 has a header format I have not seen before, @arteymix do you know it? The device seems to be in the fifth field?

TAAATGTT:@NS500264:224:HWJ37BGXY:1:11105:12161:2145:GTCGATGAGACTAGCCATCGCATTGCCACCACTACCTCTGAGCTGAAGAGTGAACGTAAATGTTGACT length=75

**Comment by sanjarogic** [comment]
I am adding another example here: [GSE153823](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=19041). I am not sure if we've seen this format before, but it got "no batch info" badge in Gemma.

Here are the first few headers:

@SRR12150087.1.1 D00408:130:1:1101:1455:2201 length=50
@SRR12150089.1.1 D00408:130:1:1101:1929:2244#CGCTCATT length=50
@SRR12150094.1.1 D00408:130:1:1101:1340:2234#ATTCAGAA length=50
@SRR12150081.1.1 D00408:130:1:1101:2051:2206 length=50
@SRR12150097.1.1 D00408:130:1:1101:1521:2216 length=50
@SRR12150078.1.1 D00408:130:1:1101:1599:2216 length=50
@SRR12150098.1.1 D00408:130:1:1101:1800:2205 length=50

**Comment by ppavlidis** [comment]
I want to try to summarize the supported header situation, but it's kind of messy.

There are two basic formats (omitting that we also use the platform e.g. GPL). The examples use the ":" delimiter, but we also accept "_".

```
Format 1 (first 7 fields are "standard" but there can be more):  <machine_id>:<run number>:<flowcell ID>:<lane>:<tile>:<x-pos>:<y-pos> <read>:<is filtered>:<control number>:<index sequence>; we can use the first four fields
 ```

```
Format 2 (5 fields):  <machine_id>:<lane>:<tile>:<x_coord>:<y_coord>; we can use machine and lane.
```

There is a variant of format 1 that has only 6 fields, that includes `<device>:<flowcell>:<lane>`

D00408:130:1:1101:1455:2201 length=50 has 6 fields. The first field looks like a device, third might be lane. Second I don't know, but those three look potentially usable. I'm not sure whether it is being mishandled or not but since we don't have documentation of these formats, it's a little disconcerting. I would be reassured with more examples that don't have constant values for those three fields.

**Comment by ppavlidis** [comment]
GSE153823 has 30 samples, all with the same first three fields, I'm skeptical that's a single lane - isn't that a high level of multiplexing? The GEO record and paper doesn't provide such details.
