### ISSUE TITLE
Dataset Experimental Design display displays NaNs for data that is not missing

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#984]
I thought this was a curation issue at first but only seems to be present in the dev server

https://dev.gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=3610

Experimental Design window shows every age as a NaN. 

An api request to the dev server gives the correct ages

 https://dev.gemma.msl.ubc.ca/rest/v2/datasets/3610/samples

**Comment by arteymix** [comment]
@Mahanrn already noticed that, it's a regression caused by how factor values serialization changed in the 1.31 series. It's already fixed.

**Comment by arteymix** [comment]
Take a look at https://staging-gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=3610
