### ISSUE TITLE
Biomaterial editor: allow raw characteristics to be copied or turned into factor values.

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#987]
Example of relevance: https://github.com/PavlidisLab/GemmaCuration/issues/464

For large data sets, populating factors can be time consuming and/or error prone. When the GEO record has a relevant Sample characteristic (Biomaterial->characteristic in Gemma, displayed as "raw characteristics" in the biomaterial editor), we should leverage that better than we do.

This is helped by changes to the format and display of biomaterial characteristics in the biomaterial editor.

For categorical factors, unless there are many levels, the curators can use the relevant raw characteristic column as a guide so it's not a big win to be copying things over.

But for continuous factors like "Age in years", it would save a lot of manual work to simply be able to copy the numerical values from the raw characteristic to a factor.

The GUI for this would require a way to indicate the source raw characteristic, and the target factor. We'd need to decide how it would work exactly:

* For categorical factors, it makes more sense to "initialize" a new factor using the characteristics; then in the Design setup tab, curators could edit the category and terms for each factorvalue.
* If on the other hand we want to populate an existing factor, we'd need a way to map the raw strings to the more formal factorvalues. The curator would need a GUI to do that, but I'm not sure this is worth it.
* For continuous factors, it could be done either way, since the values are just numbers -- but are stored as strings in the Characteristic.value.

I'm not sure but I think it's possible to add items to the column context menu in an Ext.js table.

**Comment by arteymix** [comment]
I think the best way would be to have a DWR endpoint that creates the factor with all the possible values and assign the FV to the individual samples. It would also handle categorical factors.

In the interface for creating a new factor:

![image](https://github.com/PavlidisLab/Gemma/assets/1318477/bbedc6ef-ff54-43ee-b342-00b925de5485)

we can add an option to prepopulate from sample characteristics.

**Comment by ppavlidis** [comment]
I've added a working implementation of this idea, probably needs more testing

**Comment by arteymix** [comment]
It's in the 1.31.1 branch, so it will be deployed on the staging server for further testing.
