### ISSUE TITLE
Baseline is not being recognized when DEA is run using CLI

### ISSUE THREAD

**Issue by SalvaSherif2532** [PavlidisLab/Gemma#989]
This issue has come up multiple times and seems to be resolved by refreshing the DEA on the UI itself. When DEA is run using the diffExAnalyze CLI, the baseline terms "control", "reference subject role", "reference substance role" are not automatically identified and used. Rather it arbitrarily chooses the other FactorValue as the baseline. I also notice that this occurs when the baseline term is the object rather than the subject.

There is no warning or error showing up in the logs, this is the only indicator that something is off.
 INFO 13239 [main] u.g.c.d.m.ExpressionDataMatrixColumnSort.getBaselineLevels(173) | Falling back on choosing baseline arbitrarily: FactorValue 231307: phenotype:

I'm assuming this is a bug of some sort.

**Comment by arteymix** [comment]
I've adjusted the baseline detection scheme to account for statements. However the CLI is currently not aware of the new way we can mark FVs as baseline as it is still using the 1.30.

The staging version of the CLI should not have this issue. I think you can use it by setting GEMMA_CLI_VERSION to 1.31.0.

**Comment by arteymix** [comment]
As this is resolved by refreshing in the GUI, it's pretty clear to me now that this will be resolved when rolling out the 1.31.
