### ISSUE TITLE
GSE233750 - Outlier removed but still showing up as a possible outlier

### ISSUE THREAD

**Issue by delphineyz** [PavlidisLab/Gemma#990]
[GSE233750](https://staging-gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE233750&tab=admin) shows D7_M.ONC.D7.4.200124 as a possible outlier and removed outlier after refreshing diagnostics.

**Comment by ppavlidis** [comment]
That's not what I'm seeing on staging, it just says the outlier was removed.

<img width="234" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/c4b323e2-8a96-4fcf-83f8-59c277e813c7">
