### ISSUE TITLE
Add a page or a redirection to the Phenocarta dump

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#992]
@ppavlidis recently removed all the Phenocarta data we have a dumped it into a flat file format.

We still have a link that serves Phenocarta. This should be retired prior to the scheduled cleanup in the 1.32 and converted either in a 404 or a redirection to the data dump.

I'll add in more details when I'm back.

**Comment by ppavlidis** [comment]
Because phenocarta contained some proprietary data that we kept private (namely OMIM) we have to remember to remove that from the dump we share.

**Comment by arteymix** [comment]
Now serving a 404 page. We can revisit this when we decide what to do with the Phenocarta dump.
